### ISSUE TITLE
Server crash RANDOMLY.

### ISSUE THREAD

**Issue by XDqrkneZ** [pmmp/PocketMine-MP#1023]
### Steps to reproduce the issue

1. ... Well, my server crash every 2-10 minutes and I don't have any idea why
2. ...

### OS and versions

* PocketMine-MP: See crashdump
* PHP: See crashdump
* Server OS: See crashdump
* Game version: PE/Win10 (delete as appropriate)

### Crashdump, backtrace or other files

CRASHDUMP 

https://pastebin.com/73TzJwJK
* ...

**Comment by ZizzyZizzy** [comment]
```
PocketMine-MP version: 1.6.2dev #154 [Protocol 113; API 3.0.0-ALPHA5]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux vps130303 4.4.0-78-generic #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017 x86_64
PHP Version: 7.0.3
Zend version: 3.0.0
OS : Linux, linux
```

Start by updating your your PurePerms. v1.4.1 is available and fixed for 1.1.0.X Pocketmine.

I'm certain you need other plugin updates as well, considering you have 38 different plugins installed. From first-hand experience, plugin developers are slow to keep up with the blazing speed of dktapps.

**It's always wise to disable ALL plugins then test again before opening a bug report here, otherwise you're just wasting the Pocketmine developers' time and effort.**

**Comment by Qimie** [comment]
True

**Comment by XDqrkneZ** [comment]
Thanks and sorry fam @ZizzyZizzy

**Comment by SOF3** [comment]
You have zero ideas why, and we have negative ideas why.
