### ISSUE TITLE
Need to change StandingSign to SignPost on API3/blocks

### ISSUE THREAD

**Issue by Enrick3344** [pmmp/PocketMine-MP#1024]
### Issue description

getting some error with some other plugin because its no longer StandingSign its SignPost!

### OS and versions

* PocketMine-MP:
* PHP:
* Server OS:
* Game version: PE/Win10 (delete as appropriate)

### Crashdump, backtrace or other files

* ...

**Comment by jrodr10** [comment]
Plugin Issue #Close ._.

**Comment by Qimie** [comment]
Why is Linux on PMMP now?!?!??! Is he trying to take over this repo now.
Get the flip out of here.

**Comment by ZizzyZizzy** [comment]
If it was changed in the Pocketmine source, it's because Mojang changed it. Plugin developers need to keep up. The block is now called SIGN_POST:

`self::$list[self::BURNING_FURNACE] = BurningFurnace::class;
self::$list[self::SIGN_POST] = SignPost::class;
self::$list[self::WOOD_DOOR_BLOCK] = WoodDoor::class;
`

**Comment by SOF3** [comment]
api3/blocks was never guaranteed to be backward-compatible.
