### ISSUE TITLE
Disconnects don't work correctly under some circumstances

### ISSUE THREAD

**Issue by Muqsit** [pmmp/PocketMine-MP#1026]
### Issue description

When PlayerLoginEvent gets cancelled, `PlayerLoginEvent::getPlayer()` would not get the kick message and will have to wait for "Building Terrain" to change to "Disconnected from Server". PlayerPreLoginEvent, on the other hand, when cancelled, is guaranteed to show `PlayerPreLoginEvent::getKickMessage()`.
### Steps to reproduce the issue

1. Set PlayerLoginEvent's kick message to something
2. Cancel PlayerLoginEvent
```php
public function onLogin(PlayerLoginEvent $event){
    $event->setKickMessage("test");
    $event->setCancelled();
}
```
### OS and versions

* PocketMine-MP: f0d12a0
* PHP: 7.0.19
* Server OS: Ubuntu 14.04
* Game version: Win10 (happens on PE too)

**Comment by dktapps** [comment]
This is likely because of a workaround I added to the core to prevent plugins accidentally crashing clients by sending bad packets before StartGamePacket. I'm not sure how this can be cleanly fixed.

**Comment by dktapps** [comment]
If you revert commit 087a994393be23f694c6d0585bcd3797a15bf50b the issue does not occur. However as stated in the commit it is a workaround and I'm not sure it should be removed at this point.

**Comment by dktapps** [comment]
This appears to be a bug in RakLib. The server should not be sending ID_DISCONNECTION_NOTIFICATION unless it has shutdown. In the case of PocketMine, we probably don't even want to do that due to server shutdown messages.

**Comment by mal0ne-23** [comment]
can we just make PlayerLoginEvent unable to be cancelled and tell people to use PlayerPreLoginEvent->setCancelled(true);? Could be part of the api updates in ALPHA-6

**Comment by SOF3** [comment]
@mal0ne-23 A bug in the network backend should not unnecessarily lead to limitations in the API.

**Comment by mal0ne-23** [comment]
yeah.. bad idea

**Comment by dktapps** [comment]
So, disconnection notification notwithstanding... The cause of this bug is rather stupid.

MCPE DisconnectPacket is sent as reliable-ordered, but with immediate priority. The issue with this is that the order indexes are assigned when the packets are _queued_, not when they are sent. So you have the StartGamePacket sitting inside an encapsulated packet, queued to be sent reliably, and then the DisconnectPacket jumps the queue.

The effect of this is that RakNet on the client-side will sit... and wait... for the rest of the packets to come in so that they can be ordered correctly. However, the problem with this is that once RakLib sessions are closed, the rest of the queue is not sent... so the client just sits and waits for packets that are never going to arrive, until it times out.
