### ISSUE TITLE
Plugin dependency changes

### ISSUE THREAD

**Issue by TheDiamondYT1** [pmmp/PocketMine-MP#1227]
### Introduction

Change plugin.yml `depend` and `soft-depend` attributes to allow version numbers, like the `extensions` attribute.

Also have a configuration option to allow checking if a plugin dependency is on Poggit, and download it if it is.

##### The good ol' method
```yaml
depend: [Switchbox]
```
Loads correctly.

```yaml
soft-depend: [Switchbox]
```
Loads correctly.

##### Version wildcard
```yaml
depend:
  Switchbox: "*"
```
Loads correctly.

#### Plugin absent
```yaml
depend:
  Switchbox: "*"
```
Fails to load: see bottom

##### Using a string as a true version constraint

Note: > is a special symbol in YAML. Always Quote the version constraint.

```yaml
depend:
  Switchbox: ">=3"
```
Loads correctly.

##### Using a string as a false version constraint
```yaml
depend:
  Switchbox: "<>3.1.6"
```
Fails to load: see bottom

##### Using two true version constraints
```yaml
depend:
  Switchbox:
    - ">=3"
    - "<4"
```
Loads correctly.

##### Using one true version constraint and one false version constraint
```yaml
depend:
  Switchbox:
    - ">=3"
    - "<>3.1.6"
```
Fails to load: see bottom

##### Without Poggit checking
```
[19:16:20] [Server thread/ERROR]: Dependency plugin Switchbox not found.
[19:16:20] [Server thread/CRITICAL]: Could not load plugin 'Test'
```

##### With Poggit checking
idk.
```
[19:16:20] [Server thread/NOTICE] Dependency plugin Switchbox not found locally, but found in Poggit. The plugin will be downloaded in the background.
```

#### Incompatible version
totally didnt copy from the extensions pull request. heh.
```
[19:16:20] [Server thread/ERROR]: Dependency plugin Switchbox has an incompatible version (3.1.6 not <>3.1.6) specified in plugin 'Test'.
[19:16:20] [Server thread/CRITICAL]: Could not load plugin 'Test'
```

you get the idea

**Comment by SOF3** [comment]
While Poggit is the official plugin repository, it is inadvisable to add its API into PocketMine right now, because of multiple reasons:

1. Poggit is still in beta phase, and we haven't had a finalized API yet.
2. We don't want to give the perception that we are hard-selling Poggit, just like Paper is doing with their Timings v2.

Regarding the versions for dependency plugins:

* We are [encouraging use of Semantic Versioning](https://github.com/poggit/poggit/commit/7bc96f5c04a6b61ca286d41809e424a821b35252) in plugins, so [semver/composer-compatible version constraints](https://getcomposer.org/doc/articles/versions.md) might be more appropriate.
* Otherwise, not all plugins use a versioning scheme compatible with version_compare(). The versions for extensions were created based on the assumption/observation that almost all of the extensions we commonly use are compatible with version_compare().
* For example, some plugins (not that we encourage so) use version names with codename prefixes (e.g. `Alpha_1.4`, `Zekkou Cake 5.2`, etc.), which cannot be used well with `version_compare`.

As a result, I hesitate to add such feature to dependency plugins.
