### ISSUE TITLE
Shooting issue

### ISSUE THREAD

**Issue by ScandiePlay** [pmmp/PocketMine-MP#128]
### Issue description

When shooting with a bow, an arrow goes down everytime.

### Steps to reproduce the issue

1. Take a bow and an arrow
2. Shoot and look.

### OS and versions

* PocketMine-MP: My server is running PocketMine-MP 1.6.1dev 「Unleashed」 implementing API version 2.1.0 for Minecraft: PE v0.16.0.5 alpha (protocol version 91), hash - 763ef7f937dea184d608900fb8dc2efdc6c1a8c7
* PHP: 7.0.3
* Server OS: Ubuntu 14.04
* Game version: PE, v.0.16.1

### Crashdump, backtrace or other files

* ...

**Comment by ScandiePlay** [comment]
Tried to change the core from Genisys to PocketMine-MP - got an issue =)

**Comment by dktapps** [comment]
Genisys is irrelevant.

**Comment by judithdrive** [comment]
Are you pulling the bow enough? Hold on 'use' until the bow is stretched back as far as possible.

**Comment by ScandiePlay** [comment]
Pulling enough. I can give an IP and a port of my test server if you want to see.

**Comment by SOF3** [comment]
@ScandiePlay no thanks, everyone can start their own server according to the reported versions.

Is the arrow falling in the manner such that it is bouncing like when you shoot an arrow at another player in creative mode in MCPE local multiplayer? I suspect this issue to be caused by collision of the arrow with the shooter, probably related to server lag.
