### ISSUE TITLE
API minor version bump request on declaration changes?

### ISSUE THREAD

**Issue by ZizzyZizzy** [pmmp/PocketMine-MP#1340]
### Issue description
@dktapps - I know you're hard at work every day updating source code and making it better, and the entire Pocketmine community is very appreciative of your contributions.

However, when one little thing changes in a public function, such as adding a requirement for an additional parameter (BaseEntity::attack() now needs $damage), it breaks previously working plugins that were updated to match the current API version.

An ALPHA7 API PMMP build from July was working fine with PureEntitiesX 0.2.2, for example. That one little declaration change in BaseEntity required updating 20+ PureEntitiesX files to make it compatible with the August 20th PMMP build, which is still tagged as 3.0.0-ALPHA7 API.  This makes it horribly confusing to the Pocketmine plugin developers and server owners trying to keep their server updated, since a plugin that is supposedly ALPHA7 compatible suddenly breaks with the latest PMMP update, since the API version did not change.

It's a nightmare to attempt to track which PMMP build works with which plugin version because the API version has not actually changed.  When declarations are changed like that, it seems prudent to update the API minor version (ALPHA8 ??) to let everyone know plugins might break, and give them a chance to label their plugin version as compatible with specific minor API versions.

Any suggestions/actions on this are much appreciated. We don't want to scare away the plugin developers with a bombardment of bug reports every time a declaration changes. "My plugin IS compatible with ALPHA7." "Yes, it was yesterday, but changes **today** broke that compatibility." Ugh.

Anything you can do to alleviate this pain will _(should)_ only serve to help you as well, as people won't be so quick to submit a bug report here, only to be told to contact the plugin developer to keep up with the changes.

Regards.

**Comment by ZizzyZizzy** [comment]
Ugh, OK, so bad example with BaseEntity, or maybe a perfect example?

The source code released today doesn't even have the file BaseEntity.php like it did on August 7th. Furthermore, all the attack declarations are back to the versions where they didn't require $damage as a parm.

`Entity.php:     public function attack(EntityDamageEvent $source){`

Aug 7th build #06083d6 of the same file:

`Entity.php:     public function attack($damage, EntityDamageEvent $source){`

So, yeah. That.

**Comment by JackNoordhuis** [comment]
If you're worried about your plugins breaking I'd suggest sticking with builds in the [releases](https://github.com/pmmp/PocketMine-MP/releases) section. This way you don't have to constantly update your plugins after every API change.

**Comment by SOF3** [comment]
The ALPHA7 API has not been finalized yet, as Jack said.

**Comment by ZizzyZizzy** [comment]
@JackNoordhuis The last release in there is over a month old, which is a lifetime for Pocketmine. In that time there have been many stability and gameplay fixes on the master branch for ALPHA7, which has been the master branch for a long time now.

Don't underestimate the power of 1000 screaming Pocketmine players that want their updates...ugh

**Comment by JackNoordhuis** [comment]
@ZizzyZizzy The last release is a snapshot from before the API was bumped meaning it will not undergo any further changes which means you won't have to update your plugins. You're better off only using releases so you aren't constantly updating plugins due to API changes, you may miss out on getting the latest features first but you will get them when they are somewhat more stable.

If you wish to continue this discussion I'd move it to the [forums](https://forums.pmmp.io/) as this is not an issue relevant to the source code.

**Comment by dktapps** [comment]
However, he does have a point... ALPHA7 release is overdue to the point where lots of people are already using it thinking it's safe to do so. I hadn't planned on tagging ALPHA7 yet because there are still lots of bugs to fix and things to do, but it might be a good idea to release it regardless (before the changelog gets any larger too >.>).
