### ISSUE TITLE
php binaries for windows don't have leveldb

### ISSUE THREAD

**Issue by rdstonech** [pmmp/PocketMine-MP#1530]
### Issue description
Php binaries for Windows don't have leveldb extension, that is how it should be?

### Steps to reproduce the issue

1. Download php-build-scripts
2. Start windows-compile-vs.bat
3. Wait for compilation

### OS and versions

* PHP build scripts: https://github.com/pmmp/php-build-scripts/commit/a2642ef8266b29c7a7e132acf17c0129fee7df7f
* Server OS: Windows 10 x64

![image](https://user-images.githubusercontent.com/31804440/32559371-090fbcec-c4b8-11e7-8d8b-fdf9b9eda206.png)

**Comment by dktapps** [comment]
the leveldb bindings for PHP (as seen in https://github.com/pmmp/php-leveldb) is not currently considered stable enough for production and as such is not included by default. If you want it, you'll have to compile it yourself.

Additionally, leveldb worlds from MCPE 1.2 are not currently supported because I haven't had the time to update the implementation.

**Comment by rdstonech** [comment]
@dktapps Okay, sorry for issue. I'll use Anvil :D
