### ISSUE TITLE
Can't place boat onto water

### ISSUE THREAD

**Issue by feikede** [pmmp/PocketMine-MP#1828]
### Issue description

Can not place a boat onto water, tried oak boat. Tried several places, day and night.

Want to place my oakboat onto water like written here: https://www.digminecraft.com/getting_started/how_to_use_boat.php
Result: Boat stays in inventory.

### Steps to reproduce the issue

1. Craft a boat
2. Place onto water

### OS and versions

* PocketMine-MP: V 1.7dev Build #518 (15.12.2017 16:48:31) 
* PHP: PHP 7.2.0RC6 (cli) 
* Server OS: suse linux aarch64 raspberry pi 3. 
* Game version: PE 1.2.6 iOS and android

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here 

* ...

**Comment by dktapps** [comment]
Boats are not implemented yet. As per the release notes:

> This version is an alpha - it is not feature complete. Please do not create issues for missing gameplay features.

Also, I notice you are using a development build. Please prefer using a build from https://github.com/pmmp/PocketMine-MP/releases , since these are locked into a known state. Development channel builds can have breaking changes from build to build without notice.

**Comment by JackCrispy** [comment]
Update on this feature?
