### ISSUE TITLE
Server use only one core

### ISSUE THREAD

**Issue by Frago9876543210** [pmmp/PocketMine-MP#1905]
### Issue description
For some reason my server use only one core. 
![image](https://snag.gy/eF8Kn3.jpg)

### OS and versions
* PocketMine-MP: a0683db
* PHP: 7.2.1
* Server OS: Linux Debian 8.6 jessie

**Comment by Frago9876543210** [comment]
Why "Invalid"?

**Comment by Driesboy** [comment]
check your pocketmine.yml and set the cores to 4

**Comment by Frago9876543210** [comment]
![im](https://snag.gy/TzIwcm.jpg)

**Comment by kenygamer** [comment]
@Frago9876543210 Yes.

**Comment by Frago9876543210** [comment]
I already had it installed in the config.

**Comment by dktapps** [comment]
It's invalid because it's not a bug.

You're far from the first person to notice this. PocketMine is well known for being main-thread biased.

**Comment by Frago9876543210** [comment]
@dktapps what can you recommend?

**Comment by kenygamer** [comment]
@Frago9876543210 Get a good CPU with high GHz per core.

**Comment by dktapps** [comment]
Due to the nature of PHP pthreads it is particularly inconvenient to do anything about this. If you search this issue tracker, the old repo issue tracker, and countless forks and spoons, you will find that the same question has been asked many times. I don't care to go into detail on why PHP threading is such a pain in the ass.

Work is being done to break things down into more independent things that can be threaded, however this is ongoing and extensive work, and again due to the nature of PHP pthreads has to be kept away from anything involving plugins. Don't expect magic.

Things such as network chunk serialization and compression use the async workers, as does level generation. Work is planned for the future to split network into more threads (zlib compress/decompress has a drastic impact on performance) and testing is in process to move chunk I/O onto per-level threads (see #1895).

For getting the best out of PocketMine as it is now, I suggest you read this: http://forums.pocketmine.net/threads/importance-on-hardware-memory.9379/
It's a few years old, but still very much relevant.

**Comment by kenygamer** [comment]
https://www.soyoustart.com/us/game-servers/

**Comment by optimusprime338** [comment]
I use top server from them.. performance is bad!! when comes to load 40+ players better go to ovh directly @kenygamer
