### ISSUE TITLE
Some players cannot connect to the server. (Again)

### ISSUE THREAD

**Issue by zKoz210** [pmmp/PocketMine-MP#1933]
### Issue description
The problem still exist. I think, that could be like a continuation of issue https://github.com/pmmp/PocketMine-MP/issues/1505.
Now the problem appears so the player is connected in a console, but the game client displays “locating server” and afterwards “disconnected from server”

### Steps to reproduce the issue
I'm sorry, but I don't know. This is manifested from half of my players.

### OS and versions
* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/d728154e87b0383bba5814a72c1c3a0f60f2e3f5
* RakLib: https://github.com/pmmp/RakLib/commit/998af685be51d6ee8a1e206066ccd96c21450bfd
* PHP: 7.2.1
* Server OS: CentOS 7.4.1708
* Game version: PE/Win10

### Plugins
- Server are tested without plugins.

### Crashdump, backtrace or other files
```
[03:43:22] [RakLibServer thread/DEBUG]: Created session for 192.162.35.203 47772 with MTU size 1492
[03:43:22] [Server thread/DEBUG]: RFulkren is logged into Xbox Live
[03:43:34] [Server thread/INFO]: RFulkren[/192.162.35.203:47772] вошел с id сущности 23 на (survival, -2728.3154, 69.5387, 1688.4355)
[03:44:12] [RakLibServer thread/DEBUG]: Closed session for 192.162.35.203 47772
[03:44:12] [RakLibServer thread/DEBUG]: Ignored connected packet from 192.162.35.203 47772 due to no session opened (0xc0)
[03:44:12] [RakLibServer thread/DEBUG]: Ignored connected packet from 192.162.35.203 47772 due to no session opened (0xa0)
[03:44:12] [Server thread/INFO]: RFulkren[/192.162.35.203:47772] отключился: client disconnect
```

**Comment by kenygamer** [comment]
This issue brings me so many memories...

**Comment by loneliplay** [comment]
I am too have this problem. Logs clear
7:04:43] [Server thread/INFO]: Loading pocketmine.yml...
[17:04:43] [Server thread/INFO]: Loading server properties...
[17:04:43] [Server thread/INFO]: Selected English (eng) as the base language
[17:04:43] [Server thread/INFO]: Starting Minecraft: PE server version v1.2.7
[17:04:43] [Server thread/WARNING]: Online mode is disabled. The server will not verify that players are authenticated to Xbox Live.
[17:04:43] [Server thread/WARNING]: While this makes it possible to connect without internet access, it also allows hackers to connect with any username they choose.
[17:04:43] [Server thread/WARNING]: To enable authentication, set "xbox-auth" to "true" in server.properties.
[17:04:43] [Server thread/INFO]: Opening server on 0.0.0.0:19133
[17:04:43] [Server thread/INFO]: This server is running PocketMine-MP version 1.7dev-516 "[REDACTED]" (API 3.0.0-ALPHA10)
[17:04:43] [Server thread/INFO]: PocketMine-MP is distributed under the LGPL License
[17:04:43] [Server thread/INFO]: Loading recipes...
[17:04:43] [Server thread/INFO]: Loading resource packs...
[17:04:43] [Server thread/INFO]: Loading DevTools v1.12.8
[17:04:43] [Server thread/INFO]: Enabling DevTools v1.12.8
[17:04:43] [Server thread/INFO]: Loading source plugin API v0.1 beta
[17:04:43] [Server thread/INFO]: [DevTools] Registered folder plugin loader
[17:04:43] [Server thread/INFO]: Preparing level "world"
[17:04:43] [Server thread/INFO]: Enabling API v0.1 beta
[17:04:43] [Server thread/INFO]: [API] Плагин Включен
[17:04:43] [Server thread/INFO]: Starting GS4 status listener
[17:04:43] [Server thread/INFO]: Setting query port to 19133
[17:04:43] [Server thread/INFO]: Query running on 0.0.0.0:19133
[17:04:43] [Server thread/INFO]: Default game type: Survival Mode
[17:04:43] [Server thread/INFO]: Done (0.344s)! For help, type "help" or "?"

**Comment by dktapps** [comment]
@zKoz210 can you reproduce this?

Please try reverting https://github.com/pmmp/RakLib/commit/2f1c79abfaed27cc34e2d82b1e8888d7d9fc22d9 and see if the bug still occurs. Thanks.

**Comment by zKoz210** [comment]
@dktapps Yes, now player can join to the server. 

I would like you to tell me whether there are any negative aspects, if you set the mtu size is 1432?

**Comment by dktapps** [comment]
@zKoz210 yes, it's a significant waste of bytes.

However, I pushed a commit (https://github.com/pmmp/PocketMine-MP/commit/0c868b16b6a1e2b1fd9883b4b06c9cb25b6e5678) to allow you to override the maximum MTU size manually, so have a play with that.

**Comment by zKoz210** [comment]
But how is it https://github.com/pmmp/RakLib/blob/master/server/OfflineMessageHandler.php#L50? 

I once tried to set 1432 not changing this line, and players could not come, or i'm mistaken?

**Comment by dktapps** [comment]
That line is correct. It matches RakNet. The MTU size is supposed to include the sizes of the IP and UDP headers.

If you're using an old shit router, try dropping the MTU size to 1404.

**Comment by zKoz210** [comment]
@dktapps thank you so much for option in configuration. I will try soon to check it out. Yet do not close issue please.

**Comment by dktapps** [comment]
Previously 1432 would have worked, because internally RakLib was capping it to 1432 - 28 bytes (this was a long and many-stage refactor) so the actual MTU size would have been 1404. So try 1404 with latest commits and see if it works.

**Comment by mal0ne-23** [comment]
I have this problem aswell. Only some players cannot connect.

**Comment by NikeboyHU** [comment]
I have this problem. No idea fix this :/

**Comment by dktapps** [comment]
You're all telling me you have the problem, but I still have no idea how to reproduce it, so it can't be fixed until then.

**Comment by NikeboyHU** [comment]
Raklib error in debug (the problem was here it to freeze server or crashing raklib interface, and players can't join again):
[Raklib_Error.txt](https://github.com/pmmp/PocketMine-MP/files/1656372/Raklib_Error.txt)

-----
I pasting more error with raklib, and network below:

CRITICAL TypeError: "Argument 1 passed to pocketmine\utils\Binary::writeLTriad() must be of the type integer, null given, called in phar:///PocketMine-PMMP_1.2.phar/src/raklib/protocol/EncapsulatedPacket.php on line 152" (EXCEPTION) in "/src/pocketmine/utils/Binary" at line 219
22.01 18:33:25 [Server] INFO Fatal error: Uncaught TypeError: Argument 1 passed to pocketmine\utils\Binary::writeLTriad() must be of the type integer, null given, called in phar:///PocketMine-PMMP_1.2.phar/src/raklib/protocol/EncapsulatedPacket.php on line 152 and defined in phar:///PocketMine-PMMP_1.2.phar/src/pocketmine/utils/Binary.php:219
22.01 18:33:25 [Server] INFO Stack trace:
22.01 18:33:25 [Server] INFO #0 phar:///PocketMine-PMMP_1.2.phar/src/raklib/protocol/EncapsulatedPacket.php(152): pocketmine\utils\Binary::writeLTriad(NULL)
22.01 18:33:25 [Server] INFO #1 phar:///PocketMine-PMMP_1.2.phar/src/raklib/protocol/EncapsulatedPacket.php(184): raklib\protocol\EncapsulatedPacket->toBinary()
22.01 18:33:25 [Server] INFO #2 phar:///PocketMine-PMMP_1.2.phar/src/pocketmine/PocketMine.php(391): raklib\protocol\EncapsulatedPacket->__toString()
22.01 18:33:25 [Server] INFO #3 phar:///PocketMine-PMMP_1.2.phar/src/pocketmine/utils/MainLogger.php(207): pocketmine\getTrace(1, Array)
22.01 18:33:25 [Server] INFO #4 phar:///home in phar:///PocketMine-PMMP_1.2.phar/src/pocketmine/utils/Binary.php on line 219
22.01 18:33:25 [Server] EMERGENCY RakLib crashed!
22.01 18:33:25 [Server] CRITICAL [Network] Stopped interface pocketmine\network\mcpe\RakLibInterface due to RakLib Thread crashed
-----
and next error:

22.01 19:08:01 [Server] CRITICAL TypeError: "Return value of pocketmine\item\Durable::onBroken() must be an instance of pocketmine\item\void, none returned" (EXCEPTION) in "/src/pocketmine/item/Durable" at line 91
22.01 19:08:01 [Server] CRITICAL [Network] Stopped interface pocketmine\network\mcpe\RakLibInterface due to Argument 1 passed to pocketmine\utils\Binary::writeLTriad() must be of the type integer, null given, called in phar:///PocketMine-PMMP_1.2.phar/src/raklib/protocol/EncapsulatedPacket.php on line 152

**Comment by dktapps** [comment]
@NikeboyHU please surround that in grave quotes \`\`\` ```.

Additionally, the second error looks like it's come from a spoon.

**Comment by dktapps** [comment]
Removed spoon spam.

**Comment by NikeboyHU** [comment]
It will I trying anyone more server software, and second error it same in here error with PocketMine software. Sorry, but max. some lines code changed

**Comment by dktapps** [comment]
Any update on this?

**Comment by zKoz210** [comment]
I use the mtu is 1464 and it works perfectly.

**Comment by optimusprime338** [comment]
I have been getting this issue when player trying to join servers from lobby(transfer) they get disconnected while they wont when they try direct IP! No idea its server issue? but there is no any red logs for that!

**Comment by zKoz210** [comment]
@optimusprime338 Try to make the mtu to 1464 and check again. 

![image](https://user-images.githubusercontent.com/28255085/36067937-deef35ca-0ed9-11e8-9556-022b808f989f.png)

**Comment by optimusprime338** [comment]
@dktapps Server was working good.. but I started getting this issue just after installing teaspoon(thought it will good to use it now) but even after removing the plugin I am getting this issue -.- 
![image](https://user-images.githubusercontent.com/27479208/36235450-c1648268-1216-11e8-9897-5d5eb5372f22.png)

**Comment by mal0ne-23** [comment]
more information, sometimes this occurs when connecting via VPN. Might occur more or less often depending on how close the VPN service location is to the server host

**Comment by dktapps** [comment]
I believe the VPN issue is related to differences in path MTU not being determined correctly due to VPN compressing packets. I haven't managed to reproduce that bug yet though, so it's difficult to say.

**Comment by kenygamer** [comment]
Wrong. I use VPN and it works fine.

**Comment by dktapps** [comment]
@kenygamer your connection and VPN is not the same as everyone else's. Don't be so narrow minded.

**Comment by kenygamer** [comment]
@dktapps Yes, I know. Notice the *and*

**Comment by dktapps** [comment]
your comment adds nothing to the discussion since you edited it.

also:
![image](https://user-images.githubusercontent.com/14214667/36633517-23bfdba4-198f-11e8-9fcf-18e54f1a99ca.png)
you really need to upvote yourself?

**Comment by kenygamer** [comment]
@dktapps Yeah, I upvoted for a friend that I helped to fix this in LEET servers.
