### ISSUE TITLE
Remote Connection's Throw Errors.

### ISSUE THREAD

**Issue by nathjeid** [pmmp/PocketMine-MP#1993]
### Issue description

The server seems to throw errors (but not crash) when connection with *RCON* for the first time in a run. The sent command is not executed.

- Expected result: The command should execute and throw no errors.
- Actual result: The connection fails and errors are thrown.

### Steps to reproduce the issue

1. Download `https://github.com/itzg/rcon-cli`
2. Start a new server.
3. Attempt to connect

### OS and versions

* PocketMine-MP: bf3f5532ac224dbfffccaaf1a3939cf851b8347d
* PHP: 7.2 (https://jenkins.pmmp.io/job/PHP-7.2-Linux-x86_64/22/artifact/PHP_Linux-x86_64.tar.gz)
* Server OS: Docker Alpine, Windows Linux Subsystem, Windows 10 Home

### Plugins
- N/A

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- https://gist.github.com/nathjeid/d37a457ae3ca8990288e902ebfca3ff6

**Comment by dktapps** [comment]
Your dependencies are outdated.

**Comment by nathjeid** [comment]
@dktapps The dependencies are updated... https://api.travis-ci.org/v3/job/336077074/log.txt

**Comment by dktapps** [comment]
I'm talking about the PocketMine-MP dependencies. Those classes have been moved to a new Composer library.

**Comment by dktapps** [comment]
my mistake, fixed. I assumed from the error that you hadn't installed dependencies correctly, because there's nothing that changed in RCON recently that would cause this bug. However, RCON was implicitly dependent on `Binary` being loaded prior to thread start, which previously used to be caused in PocketMine.php. This is no longer the case, meaning that the class did not exist at thread start and no autoloader was set.
