### ISSUE TITLE
Unbearable lags on weak devices

### ISSUE THREAD

**Issue by zKoz210** [pmmp/PocketMine-MP#2020]
### Issue description
Hello, by trial and error, I found out that after https://github.com/pmmp/PocketMine-MP/commit/f0696f77ef6774d6ca74ee4267d57da58477ee72 and https://github.com/pmmp/PocketMine-MP/commit/ecb3f9aeac94031f5b4f9af6d68416b0fb603b30 there were problems with the players (almost always Android device). This was expressed in the backlog of messages in the chat for 10-20 seconds, very much fell frame rate (fps), the players did not move smoothly.

I just reverted changes and everything started to work fine.

### OS and versions
* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/f66928c34571bc4b0be9e4193cbe1114ebded6e9
* PHP: 7.2.2
* Server OS: CentOS 7
* Game version: PE (Android)

### Crashdump, backtrace or other files
Video: [20180214_004748.zip](https://github.com/pmmp/PocketMine-MP/files/1722187/20180214_004748.zip)

**Comment by KennFatt** [comment]
This is what i had too, thanks for point it out here.

**Comment by dktapps** [comment]
I find that highly unlikely. Those functions are used by nothing in the core code yet.

**Comment by dktapps** [comment]
Actually, I'm blind... it's early morning here, apologies...

It looks like global packets is sending out empty compressed packets every tick. That's an odd one, because the batch mechanism ought to detect that. Removing [this line](https://github.com/pmmp/PocketMine-MP/commit/f0696f77ef6774d6ca74ee4267d57da58477ee72#diff-43a4bad7f0d5a94c78f006dae48b2370R821) should do as a temporary measure until I get round to pushing fixes for this.

**Comment by dktapps** [comment]
Should be fixed with latest master, please let me know if not.

**Comment by zKoz210** [comment]
@dktapps Thank You. Now there are no such problems, everything works perfectly!

**Comment by dktapps** [comment]
New ALPHA11 patch release will be rolling out shortly with bug fix.

**Comment by genboy** [comment]
[Runs smooth again](https://github.com/pmmp/PocketMine-MP/releases/tag/1.7dev-717) on my old weak android, great work!
