### ISSUE TITLE
Unbreakable items gives huge lag spikes to server

### ISSUE THREAD

**Issue by PainTR** [pmmp/PocketMine-MP#2029]
### Steps to reproduce the issue
1. ... I give myself an iron pickaxe with this command: /give p iron_pickaxe 1 {Unbreakable:1}
2. ... And i try to break blocks with this item and it gives huge lag spikes to server about 3-5 seconds..

### OS and versions

* PocketMine-MP: PocketMine-MP 1.7dev-699
* PHP: PHP7
* Server OS: Windows10
* Game version: Win10

### Plugins
- There are no plugins

### Crashdump, backtrace or other files
- Not giving a crashdump 

* ...

**Comment by dktapps** [comment]
That's not a lag spike. It's just the server banning your IP for 5 seconds because it hit an exception. You gave it the wrong NBT tags.

The correct usage would be `/give p iron_pickaxe 1 {Unbreakable:1b}` - note the `b`, it's important - you want a ByteTag, not an IntTag.

```
[10:33:58] [Server thread/CRITICAL]: RuntimeException: "Expected a tag of type pocketmine\nbt\tag\ByteTag, got pocketmine\nbt\tag\IntTag" (EXCEPTION) in "vendor/pocketmine/pocketmine-nbt/src/tag/CompoundTag" at line 107
```
followed by a 5-second IP ban.
