### ISSUE TITLE
Block->getBreakTime() returns incorrect values for wrong tool tiers, Block->canBeBrokenWith() not implemented correctly

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#211]
Try to break stone with your bare hand: because Block->canBeBrokenWith() isn't correctly implemented, it calculates time to break the block as if it could be broken by hand. Same thing applies when using wrong tools on blocks.

**Comment by cancrackmurder** [comment]
I would create a pull request, with the correct hardness and resistance values for currently existing blocks. (so that you can focus on other stuff instead of checking the wiki for every block)

And thx for banning my second account btw, i simply were trying to help, no idea why you don't want help on a community project.
Ban this one and i come back with a new one. Have fun.

**Comment by SOF3** [comment]
Looking forward to actual help as opposed to claims to create pull requests. Thank you.

**Comment by dktapps** [comment]
This is important for block-breaking animations to work correctly in 1.1.

**Comment by zKoz210** [comment]
@dktapps You can add it to master?
