### ISSUE TITLE
New Blocks

### ISSUE THREAD

**Issue by Enrick3344** [pmmp/PocketMine-MP#216]
Would it be possible in the mcpe-1,0 branch to add Some of the new End Blocks and Items like Ender Pearl, Eyes Of Ender, Elytra, And The End Blocks please.

**Comment by dktapps** [comment]
Please read open issues before opening a new one. I have no intention of adding these in the near future because I'm planning to rewrite the block and item API (see #179 ) so I don't fancy wasting my time adding to mess that I'm going to be rewriting anyway.

BTW: that branch is not intended for consumer use, it's highly unstable. Best not to use it at all if possible.

**Comment by Enrick3344** [comment]
Okay I Am sorry

**Comment by Enrick3344** [comment]
@dktapps when this recoding will be done, are you gonna replace the master branch by your new code? because I can only use Phar so i am using the one on Jenkins.

**Comment by dktapps** [comment]
Yes, of course. It's just on a branch at the moment because it's currently undergoing very large changes and I don't want to merge it to master until it's stable.

**Comment by Enrick3344** [comment]
Okay Thanks for the help:)
