### ISSUE TITLE
 RFC: Mobs and MobAI

### ISSUE THREAD

**Issue by 95CivicSi** [pmmp/PocketMine-MP#2380]
## Issue Description
Many users of PocketMine-MP desire / or expect to have mobs as part of the basic features.  Lack of mobs means that survival type servers have to rely on other means for items that would normally be available as drops from mobs, (food, bones, leather, etc).

## Problems
The current solutions for adding MobAI into PMMP are missing significant features and have complications that are difficult or impossible to overcome and properly implement vanilla like behavior.  Additionally, introducing MobAI has the potential to drastically change performance.

## Proposal
Executed in a series of PRs, it should be possible to implement many things related to mobs.  The addition of these items would need to be balanced based on performance impact and server owner needs.
 - The ability to spawn all mobs via:
   - Spawn Eggs
   - /summon command
   - Auto Spawing
   - Chunk Generation
 - Vanilla features
   - Breeding
   - Riding
   - Shearing
   - Taming
 - Basic Movement

*Basic movement would **NOT** include things like wolves hunting sheep or path finding.*
## Comments
I would like comments and feedback about what features are most important to players, and what the PMMP team feels would be best to leave out of PocketMine for the sake of performance.

**Comment by ZizzyZizzy** [comment]
Having even just a few of the original mobs would be a great start. Survival is non-existent without some mobs, which is rather disappointing to most people when they first play on a PMMP server.

Having Creepers, Skeletons and Zombies auto-spawn like they do in Vanilla would be a great start for hostile mobs.

Chickens, Cows, and Sheep at a minimum for friendly mobs, since that would allow for crafting food,  arrows and a bed. Breeding and shearing would be important here.

**Comment by kenygamer** [comment]
@ZizzyZizzy I agree with you. Mobs Re a fundamental piece of the survival gamemode, however, (directed to @95CivicSi and @ZizzyZizzy) implement mob API has two major problems:
- The server perfomance
- The hardness of being bug-free

PureEntitiesX has left it shown how server perfomance gets impacted drastically. Spawn 100 mobs and your server TPS will be in the clouds.
