### ISSUE TITLE
RakLibInterface: Arbitrary crash server when kick player because of the flight

### ISSUE THREAD

**Issue by zKoz210** [pmmp/PocketMine-MP#2406]
### Issue description
Crash the server when kick the player from the server because of the flight.

### Steps to reproduce the issue
I do not know may reproduce the problem. This is the server to teleport to other servers, a player 3 times I entered normal and after that crash occurs.

### OS and versions
* PocketMine-MP: **API 3.2** (https://github.com/pmmp/PocketMine-MP/commit/4006be35d900325b6d29a1a962b54ba0231c37c5)
* PHP: 7.2.8
* Server OS: CentOS 7

### Crashdump, backtrace or other files
https://gist.github.com/zKoz210/c0839f2970d0478895cb0a108e99df78

**Comment by dktapps** [comment]
this bug is impossible... either you are using an outdated version or a modified version. This bug was fixed long ago. 

Also, your line numbers do not match the supposed version. https://github.com/pmmp/PocketMine-MP/blob/4006be35d900325b6d29a1a962b54ba0231c37c5/src/pocketmine/network/mcpe/RakLibInterface.php#L166
