### ISSUE TITLE
A stable way of reading a line from terminal

### ISSUE THREAD

**Issue by SOF3** [pmmp/PocketMine-MP#2554]
There should be a documented and reliable method to thread-blocking read a message from terminal, e.g. for implementing [installation wizards](https://forums.pmmp.io/threads/plugin-installation-wizards.885/).

(Installation wizard API is another business, but there should at least be a way to do so)

**Comment by dktapps** [comment]
We have php.net for that.

**Comment by SOF3** [comment]
This is PocketMine and we have CommandReader. If a plugin uses the standard PHP way to get a line, there would be a race condition with CommandReader.

**Comment by lukeeey** [comment]
The referenced commit seems to resolve this but the issue was not closed automatically

**Comment by dktapps** [comment]
Note: This is no longer an issue for the common case if using fgets(STDIN), since ConsoleReader isn't set up until after all plugins are loaded. However, it would be problematic if plugins are loaded at runtime (though in such case it's not really desirable to halt the whole server to load a plugin anyway).

**Comment by dktapps** [comment]
Resolved by 0e806854b9a1e82b0fc30dccebeb557e7d1b69b2.
