### ISSUE TITLE
EntityFlameParticle(s) don't work anymore - 1.8 issue ?

### ISSUE THREAD

**Issue by artulloss** [pmmp/PocketMine-MP#2572]
### Issue description

Flame particles no longer work as of 1.8.

- Expected result: Flame particles to continue working after updating to 1.8
- Actual result: They don't show up as anything.

### Steps to reproduce the issue

1. Create a new EntityFlameParticle object and send it to the players location
2. Realize that there is no longer anything there as of 1.8

### OS and versions

* PocketMine-MP: 3.5.0 Release
* PHP: 7.2
* Server OS: Windows 10
* Game version: Seems to effect all

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

Well I need a plugin to make a new EntityFlameParticle, so I guess it's not an issue at all ¯\_(ツ)_/¯

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- No, this is not a crash

[Edit, didn't notice the new release, tested and as expected the issue still persists]

**Comment by dktapps** [comment]
Yes, it seems this isn't the only particle that isn't working. I can see they are working on a new particle engine, so this bug might be related. The particle ID hasn't changed, so I'm not sure what the problem is.

Part of the issue is that vanilla does not use level-events for particles anywhere (according to tommo) so it's possible that if this is broken, they won't care to fix it.

I'll continue to investigate the issue, but don't get your hopes up on it being fixed.

**Comment by artulloss** [comment]
Alright, well thanks for trying!

**Comment by Driesboy** [comment]
Yup, but the Bubble particle still isn't owrking
