### ISSUE TITLE
$e->getPlayer()->$property  = internal error

### ISSUE THREAD

**Issue by ProCompTEAM** [pmmp/PocketMine-MP#2732]
[https://pastebin.com/De06NrC3](https://pastebin.com/De06NrC3)

### Additional comments (optional)
If I using properties in plugins, server out some crash of __set($property, $value) sequrity

Bad line example: $player->logined = false;

**A few days ago the line was working!**

**Comment by dktapps** [comment]
This kind of misuse is not supported.

**Comment by ProCompTEAM** [comment]
@dktapps do I need to rewrite all plugins to a massive structure?

**Comment by dktapps** [comment]
That's your problem. You're lucky this sort of code ever worked. It's certainly not defined API.

There are better ways to do this which you should now go and explore.

**Comment by ProCompTEAM** [comment]
@dktapps can you provide a link to the commit where it worked?

**Comment by ProCompTEAM** [comment]
@dktapps corrected*

**Comment by SOF3** [comment]
Using dynamic properties would lead to clash between plugins, mismanaged memory and other unforeseen problems. It is both unsupported and incorrect to do this. If you wish to extend the Player class in private server plugins, you may use PlayerCreationEvent. Otherwise, you should maintain a list of data objects associated to each online player in your own plugin.
