### ISSUE TITLE
Introduce a new Form interface (or break the existing one)

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#2865]
## Description
The current `pocketmine\form\Form` interface sucks because it does not allow forms to serialize themselves in a context-dependent manner. For example, it is currently difficult to do translatable forms, which creates complications for third party implementations.

**Comment by SOF3** [comment]
In my opinion, this is the responsibility of the forms library. In fact, we don't even define what a `Form` is &mdash; Is it just a representation of content, like HTML? Or is it supposed to be dynamic? Is it supposed to be used on just a single player for a single time, or should we allow the same instance to be used on multiple players simultaneously, or the same player multiple times, or both? Now this gets us back to those debates we had while writing the `forms-api` branch.

Recall that the `Form` interface is there for minimalism. I don't think we can easily reach a consensus to have more than what we currently have, because that leads to a lot of decisions like object states, object lifetime, etc. Currently, libraries are doing just well. If people want to hold the same `$form` object to use on multiple players/occasions, they could just use a library that provides something like this:

```php
class DynamicForm{
    private $data; // and code to initialize $this->data
    public function send(Player $player){
        $translated = translate($data, $player->getLanguage());
        $player->sendForm(new class implements Form{
            // boilerplate to delegate variabies
            public function jsonSerialize(){ return $this->translated; }
        });
    }
}
```

There is no need to increase the complexity of what we already have just to accomplish something that could easily be implemented through libraries. (And almost everyone uses libraries for sending forms anyway)

I am voting to close this issue.

**Comment by dktapps** [comment]
It turns out that this is unnecessary because a translation-supporting form doesn't have to implement `Form` directly and can have a `Form` implementation whose sole purpose is to contain post-processed data. Forms would need to stick something over the top of `sendForm()`, but this isn't a big deal.
