### ISSUE TITLE
Problem with minecraft 1.11.4

### ISSUE THREAD

**Issue by mehrshad000** [pmmp/PocketMine-MP#2936]
hi
not work on minecraft 1.11.4

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)

**Comment by mehrshad000** [comment]
I placed these two files along with the following file, but it does not work on the minecraft 1.11.4
https://jenkins.pmmp.io/job/PocketMine-MP/lastSuccessfulBuild/artifact/PocketMine-MP.phar
https://jenkins.pmmp.io/job/PHP-7.2-Aggregate/lastSuccessfulBuild/artifact/PHP-7.2-Windows-x64.zip

https://github.com/pmmp/PocketMine-MP

Please Fix it

**Comment by iwantyouXD** [comment]
Hi Pmmp/Pocketmine-Mp.
You must update your pocketmine-mp

**Comment by iwantyouXD** [comment]
Or this file dont work at pocketmine-mp.
You must download another file.
Sorry, but i cant help you

**Comment by SOF3** [comment]
Please note that our issue tracker is not a support forum. Please do not ask for support here, and if someone did, please do not reply to them so as to discourage them ask here again next time.

Since PocketMine is only released when we are confident that normal clients are able to join, it is assumed that generic "cannot join" problems are due to personal problems with the setup. Hence, without providing specific reproducible details that sufficiently proves to be a PocketMine issue, it is assumed that the issue is a support request and shall be closed doe the sake of the cleanness of the issue tracker.
