### ISSUE TITLE
Server crashed by water flow??

### ISSUE THREAD

**Issue by CaptainDuck** [pmmp/PocketMine-MP#2995]
Link to crashdump: 
https://pastebin.com/V3EAjauQ

### Additional comments (optional)
I used a plugin that limited water flow to a certain amount of blocks then that happened.

**Comment by ZizzyZizzy** [comment]
You'll want to delete this and submit a proper request, per the guidelines that you erased when you added the text.

This report is no better than "I'm lost in the woods, please tell me where I am." No description, no name, no starting point, not even a general location/continent, nothing. How is anyone supposed to help you without providing any information? Even the crash dump is utter nonsense.

You're wasting everyone's time here, so quit being selfish and READ, then THINK before you post.

**Comment by dktapps** [comment]
don't blow your lid, the template is fine ... https://github.com/pmmp/PocketMine-MP/issues/new?template=crash.md

The crashdump provided enough information to identify the cause of the bug, but it would have been more helpful to provide the code that caused the crash, since this bug can only be triggered by a plugin's code.

**Comment by dktapps** [comment]
The bug comes from this division: https://github.com/pmmp/PocketMine-MP/blob/77a4393c7b65ebbbd3668c8af876b87bb84c0a9d/src/pocketmine/block/Liquid.php#L375

I assume you changed `getFlowDecayPerBlock()` to return `3` instead of `1`.
