### ISSUE TITLE
Detected spam

### ISSUE THREAD

**Issue by yoraze** [pmmp/PocketMine-MP#3128]
## Description
Commands on many Minecraft servers are a very important part of the gameplay.
Developers very often come up with something new, but it often happens that commands on servers require arguments.

In any case, PocketMine-MP sends the player [string: args] as arguments. This is bad, because the player simply CANNOT learn the arguments for this command, he has to enter it without arguments and is hoping for a message using this command on the server.

## Justification
Many developers use the PROTOCOL to solve this problem - they catch AvailableCommandsPacket and change the command parameters to the ones they need.

If PocketMine-MP initially sent the parameters necessary for the developer for the team, no one would use the protocol to solve the problem described above.

## Alternative methods
I saw how Altay software developers decided it.
You can see how they did it: [TuranicTeam/Altay](https://github.com/TuranicTeam/Altay/commit/586376c5f003a81cda8541976881b28c0a0b7c0b#diff-fcccc6b3539818f4a350c70efd41823c)

**Comment by dktapps** [comment]
You don't need to tell us why command overloads are useful. The fact is that nobody cares enough to do anything with them. Spoon devs have come up with hacks to display client side parameters, but such hacks typically expose the protocol to the API, and do nothing to improve the real problems with the internal command system.

This issue is about as pointless as "pls add redstone" or "pls add mobs". It's a TODO, but it's low priority because the majority of players simply don't care, and because nobody on the dev team is interested.

**Comment by dktapps** [comment]
> This is bad, because the player simply CANNOT learn the arguments for this command

This is stupid. What do you think the /help command does?

**Comment by yoraze** [comment]
> > This is bad, because the player simply CANNOT learn the arguments for this command
> 
> This is stupid. What do you think the /help command does?

The command /help should tell the player as much as possible about the command(description, arguments), but there you can only find its description. In my opinion this is not very good.

![Very informative /help command](https://user-images.githubusercontent.com/25742996/65819497-eed34000-e225-11e9-8d69-6b13f8b1bf3b.png)
