### ISSUE TITLE
Server wont start. segmentation fault. 

### ISSUE THREAD

**Issue by Tolo0** [pmmp/PocketMine-MP#322]
### Issue description
Server wont start. Segmentation fault. 

### Steps to reproduce the issue
try start the server.

### OS and versions
OS: Linux Centos 6.8
Version: I don't know. server wont start so i cant do /version.  i downloaded the master branch today.

![screenshot_20170204-131113](https://cloud.githubusercontent.com/assets/13458191/22618760/d67d650a-eadc-11e6-8941-7004b31ce113.png)

**Comment by dktapps** [comment]
1. you didn't initialize the repo correctly.
2. this is a duplicate of #90

**Comment by VoliPlays** [comment]
@Tolo0 you have instagram,I can help you

**Comment by SOF3** [comment]
@VoliPlays Please [do not use the issue tracker as a forum](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md#creating-an-issue). This is where people watch the repository to see new issues or commits of PocketMine, not a place that you subscribe to in order to get your whole mailbox spammed with people asking for help.
