### ISSUE TITLE
unable to cancel item activation without cancelling block activation

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#3267]
## Description
We need some way to fine-tune the actions that result when when right clicking on a block using an item.

## Justification
It's not possible to prevent the use of an item by clicking on a block without also preventing the clicked block reacting to click.

This is problematic in arenas where we need to prevent the use of items like spawn eggs and paintings, but we still want to allow the use of doors and trapdoors.

## Alternative methods
Providing the functionality that I mentioned, disabling painting and spawn egg, without disabling doors and trapdoors, can currently only be done by hardcoding a list of blacklisted items or whitelisted blocks.

**Comment by ColinHDev** [comment]
Currently, PlayerInteractEvent has two jobs:
- Handling the "clicking" of blocks: placing (or touching / interacting) and breaking
- Handling the interaction between items and blocks
Maybe, that should be split into two events, where one would be for the "clicking" and which cancels both block placing and breaking (where we also have an inconsistency with PlayerInteractEvent, how you mentioned on discord (cancelling PlayerInteractEvent cancels block placing, but not block breaking)), while the second would handle the interaction itself.
But, I guess, that would be a bc break since the event behaviour of PlayerInteractEvent would change and I don't know if you would like it that near the release of PM4.

**Comment by dktapps** [comment]
4.1 would be better.
