### ISSUE TITLE
start.sh change please

### ISSUE THREAD

**Issue by No4NaMe** [pmmp/PocketMine-MP#3285]
Please change the server restart cycle at start.sh for 10 seconds, otherwise the rcon pid does not have time to fall back. 

it would be nice to add a server start to the documentation
screen -AmdUS pmmp ./start.sh -l

Go to pmmp window:
The code
screen -dr pmmp

Ctrl+A+d
Close current window:
The code
Ctrl+A+k and press e

**Comment by SOF3** [comment]
Note that:
- if the server restart cycle doesn't suit your particular use case, you might want to simply write your start.sh. The start.sh file serves as a convenient startup wrapper, but you are not required to use it. You might implement your simple `while true; do php PocketMine-MP.phar; sleep 10; done` loop.
- `screen` is not even the idiomatic way to run PocketMine. There is also `tmux`, and there are also some people who want to register PocketMine as a system service, or people who run PocketMine in a Docker container. And there are also Windows users.
- Even if we have first-class support for `screen` (we actually don't), it is still not our obligation to maintain a screen cheatsheet in the readme. (Otherwise we should also document how to use SSH, how to connect to the Internet, how to use the mouse and keyboard...)
