### ISSUE TITLE
Client Crash on Join

### ISSUE THREAD

**Issue by NxtUser-HD** [pmmp/PocketMine-MP#3295]
### Issue description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### Steps to reproduce the issue
1. Try to join the server

### OS and versions

* PocketMine-MP: 3.11.5
* PHP: 7.3
* Server OS: *

### Plugins
Without plugins

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by dktapps** [comment]
I used to have a canned response for useless issues like this, but I seem to have lost it.

Don't write the issue like it's obvious what the problem is. I don't, for example, crash while connecting to `test.pmmp.io:19133`. This is therefore a specific issue and more information is needed than is provided in this generic issue.
