### ISSUE TITLE
Hello pmmp team can you kinda add this 

### ISSUE THREAD

**Issue by Scottishman** [pmmp/PocketMine-MP#3303]
Some blocks are registered in pmmp but cannot be placed and also be crafted including  Smoker,Barrel,Composter,grindstone,etc... and missing blocks.  Like I love pmmp don't get me wrong but you should atleast work on that issue because that plays a big change in building and making maps.

**Comment by jasonwynn10** [comment]
no

**Comment by Scottishman** [comment]
PMMP gets boring without new blocks

**Comment by Erkam246** [comment]
xd

**Comment by TwistedAsylumMC** [comment]
The majority of the blocks added since 1.2.13 are not compatible with world format currently used by pocketmine due to their ids being out of the id range. The blocks you listed are not registered, and you can only craft them because the crafting reciped are all inside of a json file pulled from the client.

**Comment by SOF3** [comment]
@jasonwynn10 @Erkam246  The issue tracker is not a forum nor a chatroom. Please do not respond to issues with comments that do not add any value to the issue like "no" or "xd".
