### ISSUE TITLE
Projectiles sometimes knock moving players in the wrong direction

### ISSUE THREAD

**Issue by Nerahikada** [pmmp/PocketMine-MP#3382]
### Issue description
When Projectile hits a player, the player makes a strange knockback.
https://youtu.be/u2CiA0WKfWw?t=12

### Steps to reproduce the issue
1. Throw snowballs, shoot bow

### OS and versions

* PocketMine-MP: 3.11.6
* Server OS: Ubuntu 18.04 LTS
* Game version: PE/Win10

### Plugins

```
Plugins (0):
```

**Comment by dktapps** [comment]
I don't know what I'm supposed to be looking at. Nothing is obviously wrong to my eyes here.

**Comment by Nerahikada** [comment]
The player is supposed to knockback as far as possible from the thrower.
However, there has been a knockback in the opposite direction.

**Comment by dktapps** [comment]
I remember the same problem happening to zombies when shot on the top of the head.
IIRC, the problem occurs because the projectile strikes a point _behind_ the centre of the AABB.
This causes [this code](https://github.com/pmmp/PocketMine-MP/blob/e45e84b236869b6a309a76cbd4f97176fa196515/src/pocketmine/entity/Living.php#L567-L568) to compute deltas which knock the entity in the _opposite_ direction that the projectile struck it from.

I don't currently know what the correct fix for this problem is, and I don't doubt the PvP community will hate whatever I come up with.

**Comment by dktapps** [comment]
The easiest solution to this problem seems to be to use the projectile pre-collision velocity as the direction vector for the knockback.
