### ISSUE TITLE
Poorly formatted YAML parse errors

### ISSUE THREAD

**Issue by SOF3** [pmmp/PocketMine-MP#3454]
YAML parse errors are one of the most common problems a user would encounter. However currently it is very poorly formatted. Users and plugin developers can't know which file is wrong without carefully going through the stack trace.
For users, the stack trace is too technical, and the the `yaml_parse()` prefix is not user-friendly enough to imply that a certain YAML file is wrong.
For developers, the stack trace usually involves PocketMine internals, which should not be some knowledge necessary for simply writing a basic plugin with a working `plugin.yml`.

This issue advises improvement in error handling and display with respect to `yaml_parse`. In particular, the parse in `PluginDescription` should mention that it is related to a plugin.yml file (instead of, for example, a config file), and the one in `Config` should include a user-friendly message including the file name instead of an ugly stack trace.

One may argue that it is the responsibility of developers to handle errors properly, but the whole point of `Config` is to create a convenient API specialized for config files. A try-catch that at least includes something like `Failed parsing YAML file located at %s` would be helpful, even if not correctly printed onto the logger.

(OK let's be honest... nobody prints user-friendly messages when user typed an array for a string anyway...)

**Comment by dktapps** [comment]
For posterity's sake, I'll summarise the Discord discussion here:

Most config parsing errors come from libyaml, which has terrible error messages from the get-go. This is not easy to resolve. About the most we can do is report the file path of the broken config in addition to the actual error message.

However, any change to these error messages a pain in the ass because the errors are released via the legacy error_reporting system and not exceptions.
