### ISSUE TITLE
Refine changes of Listener cancelled event behaviour (PM4)

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#3462]
## Description
One of the upcoming changes in PM4 which is likely to be problematic is the change of default handler behaviour from default handling cancelled and filtering using @ignoreCancelled, to default _not_ handling cancelled and needing to opt in using @handleCancelled.

This is a significant problem because it's a silent backwards compatibility break that's hard to detect: the places where behavioural changes will occur are the precise places where it's not possible to detect said behavioural changes. This is because handlers with no doc comments are the ones that will experience silent behavioural changes, which is impossible to detect at the point of registration, and also very difficult for a static analyser to detect, if it's even possible at all.

## Possible solution: Scrap the change and stick with PM3 behaviour
This would require the least work for migration, but it would also negate the benefits of the change and cause additional work for those who already switched to PM4.

## Possible solution: Keep the change, but require some kind of switch, a bit like `declare(strict_types=1)`
It could be possible to have some kind of class-scoped annotation on `Listener`-implementing classes like `@handlersIgnoreCancelledByDefault`. This would allow users to opt into the new behaviour on a class by class basis with minimal hassle.

## Possible solution: A new interface implemented by `Listener` classes, e.g. `PM4Listener` or `IgnoreCancelledEventsByDefaultListener`
This falls roughly in the same vein as the class-based annotation switch, except that it would apply at the type level (probably a good thing), but it would also forcibly apply to any subclass that inherits from a class implementing it (possibly bad).

**Comment by SOF3** [comment]
> It could be possible to have some kind of class-scoped annotation on `Listener`-implementing classes like `@handlersIgnoreCancelledByDefault`. This would allow users to opt into the new behaviour on a class by class basis with minimal hassle.

This defeats the point of changing to `@handleCancelled`. Nobody will remember to add this annotation, just like nobody remembered to add the `@ignoreCancelled true` annotation in the first place.

**Comment by dktapps** [comment]
That may be true. However, my interpretation is that among people who did know it existed, but @ignoreCancelled still had its (marginal) uses, just that it takes less lines to just write `if($event->isCancelled()) return` than to add `@ignoreCancelled` everywhere.

It's also possible we could have a second `Listener` interface which uses the new behaviour, instead of annotations.

**Comment by dktapps** [comment]
Updated OP with an additional possible solution.

**Comment by SOF3** [comment]
What if we remove `Listener`, and have separate interfaces for both options?

**Comment by dktapps** [comment]
I'm not sure what advantage that would offer. It would just break a bunch of existing user code for no reason.

**Comment by 95CivicSi** [comment]
Considering the other major differences that exist in the PM4 branch, current developers should be looking for these types of changes and be prepared to learn new behaviors.   As long as the provided documentation around the behavior, provides adequate information for a developer to learn how it works, the originally described method of just changing the default to not handling cancelled, should be acceptable.

A good example of a similar problems exists with how PM3 handles event priority. Many entry level developers, do not use this feature or even know about it.  This leads to unusual or unexpected behavior in many cases and is difficult or impossible to setup static analysis to catch.  The community learns about these via experience, and more knowledgeable/experienced developers direct and share info with less knowledgeable/experienced developers. It is reasonable to expect that a similar response would be repeated with this change.

Something that may be helpful would be including debug messages during listener registration, noting the listener is going to be ignored if the event is canceled when the @handleCancelled tag is not found. An additional debug message when the event handler refuses to call a listener because of this condition, may be helpful also.  I'm not sure what type of performance impact this will have though.

**Comment by SOF3** [comment]
Quoting our previous discussion from Discord, our obstacle from making decision is the lack of knowledge how many users rely on this behaviour. There are a few cases:

- User forgot/didn't know about @ignoreCancelled (so it is not declared) but plugin should actually @ignoreCancelled
  - I believe this is the very likely case. Most public plugins I find suffer from this issue.
- User forgot/didn't know about @ignoreCancelled (so it is not declared) but plugin really wants to handle non-cancelled events
  - I don't know how often this happens. How many scenarios are there that a plugin deliberately wants to handle non-cancelled events?
  - But since the developer didn't care, this change is not a problem anyway.
- User knows about @ignoreCancelled and plugin declares @ignoreCancelled true/false
  - This is good case, and we just need to nicely ask them to change.
- User knows about @ignoreCancelled and deliberately does not add @ignoreCancelled
  - This is the troublesome case. But again, what scenarios are there that plugin does not want to ignore cancelled events?

For reference, I performed [a search on Poggit to look for plugins using `setCanceled(false)`](https://poggit.pmmp.io/grepPlugins/2020-05-02-899519ad52a94e1e.html). I performed this search since intentionally handling cancelled events might imply you want to keep the event happening. If you don't want to uncancel the event but want to handle cancelled events (with awareness on `@ignoreCancelled`), why didn't you simply handle it at the LOWEST priority? (I assume people who know `@ignoreCancelled` naturally know `@priority` as well; an unsupported but quite reasonable conjecture)

Summarizing the findings,
- Some uncancel the event just to undo their own cancellation, not to undo the cancellation other plugins (which is problematic either way). Example: @TungstenVn/[Gomoku](https://github.com/TungstenVn/Gomoku/blob/1b4fd892083a4cd73aa858da0c0e00f1dd2c7437/src/TungstenVn/Gomoku/gameHandle/gameHandle.php#L322)
- Most (almost all) blindly uncancel if they think the event is ok, without caring whether other plugins wanted to cancel it for some reason (they think they're the only plugin in the world handling this event). Example: @Chalapa13/[WorldGuard](https://github.com/Chalapa13/WorldGuard/blob/78632686f46bbb557688e2e72a51919efc7f221d/src/Chalapa13/WorldGuard/EventListener.php#L189)
- Some have unexplainable logic, such as cancelling and uncancelling overwriting one another eventually unconditionally. Example: @IceCruelStuff/[RedstoneX](https://github.com/IceCruelStuff/RedstoneX/blob/ec2b68e137e14aede6de0d8f80ea9f5af0daaac5/src/RedstoneX/event/EventListener.php#L46)
- Some seem to have mistaken what `@ignoreCancelled` means, trying to check if an event was already cancelled when those calls should never have reached the plugin. Example: @SergeyDertan/[SRegionProtector-pmmp](https://github.com/SergeyDertan/SRegionProtector-pmmp/blob/512cb5479fb0256505e133d876f0a7edad73606f/src/sergeydertan/sregionprotector/event/RegionEventsHandler.php#L86-L101)
- Some seem to even ignore the plugin priority requirements, cancelling/uncancelling an event at the MONITOR priority. Example: @Crypt97/[CellPE](https://github.com/Crypt97/CellPE/blob/6ebcfa88098605c9e195cb2ddcbe1f4f3613a4f2/src/Bajan/CellPE/listener/EventListener.php#L125)
- Some reuse the event to pass into the API. This is more reasonable although unsound. But still not reasonably handleCancelled. Example: @UIPlugins/[PvPConfirmationUI](https://github.com/UIPlugins/PvPConfirmationUI/blob/aebbe6de04c892181cb2396c46aac23ce640f973/src/ARTulloss/PvPConfirmationUI/PvPConfirmationUI.php#L60)

@dktapps suggested that my search only works on public plugins (particularly those built on Poggit). But for the case of private plugins, especially "core" plugins, there are usually no other plugins running (this is an unconvincing hypothesis), and so there is no need to care whether events are cancelled.

If we adopt the behaviour to force developers specify whether they want to handle cancelled events,
this would benefit many plugins by making deeloper think whether they really want to override other plugins. The `@handleCancelled` change was done to clarify the ambiguous meaning of "ignore cancelled" (ignore cancelled events vs ignore whether it is cancelled), so renaming existing ignoreCancelled to handleCancelled benefits from the change anyway. The only use cases affected negatively would be those deliberately not cancelling the event, but a simple, directly fixable BC break for a minority of plugins would be reasonable, especially in a major version change after 2 years compared to the disaster back in 3.0.0-ALPHA7.

It is 2020, and apparently we are behind schedule breaking all plugins on the world.
![image](https://user-images.githubusercontent.com/19623715/80898604-f0bf2d80-8d37-11ea-95da-3c0a5ed4cc6e.png)

**Comment by dktapps** [comment]
> Considering the other major differences that exist in the PM4 branch, current developers should be looking for these types of changes and be prepared to learn new behaviors. As long as the provided documentation around the behavior, provides adequate information for a developer to learn how it works, the originally described method of just changing the default to not handling cancelled, should be acceptable.

oh, give me a break... updating plugins is a continuous build & run cycle, nobody spends their time poring over documentation except when the change is going to be highly time consuming. That's especially a problem in this case because the change has silent consequences which users will not even notice until they cause bugs.

Changes that blow up are OK, but we can't make this blow up without making more changes that will have impacts on all plugin developers, and for such an inconsequential change I can't justify it.
