### ISSUE TITLE
Chunk unload delay causes server memory to overfill.

### ISSUE THREAD

**Issue by madecode15** [pmmp/PocketMine-MP#352]
### Issue description
**Let's say you have a survival server, 512MB of RAM,  and maybe 40 players.**

40 players each go in different directions, south, west, north, east. They are going to travel 600 chunks away from spawn each.

PocketMine starts loading chunks as normal, but since they are moving one chunk to another in less then a minute, a lot of chunks will be loaded.

This delay makes  the server use more memory then it should.
https://github.com/pmmp/PocketMine-MP/blob/91fd99d76a32044189fd9758e205e630e24845a0/src/pocketmine/level/Level.php#L2779

Although it may not seem like much, the issue is real. In 1.4 chunks would unload instantly after  being on queue. The function was changed in this commit:
https://github.com/pmmp/PocketMine-MP/commit/8d4abe2f39b024511554d5e723721c05dec48b5e

I think the best solution is to make the unload queue delay optional for smaller servers. With the addition of transfer packet, If I want to do a system like this:
Hub select game -> Transfer to temporary game server #1

I would give the Hub more ram, and give the game server less ram because it will only hold a small number of players.

The benefits of delaying unloading chunks can be debatable too. If a chunk needs to be unloaded, why delay it? The reason it was put on queue was because it was not needed in the first place. It can  possibly be beneficial to smaller servers or mega servers with tons of RAM.

PocketMine is really over exaggerating it's terrible RAM usage.

### Steps to reproduce the issue
You can't reproduce this without having many players loading many chunks.
1. Load chunks
2. Run /status & watch them slowly unload.
Imagine this with 40~100 players who will load tons of chunks.

### OS and versions
* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/91fd99d76a32044189fd9758e205e630e24845a0
* PHP: 7
* Server OS: Mac
* Game version: Both

**Comment by dktapps** [comment]
It's better for performance to hold them in memory for a short while in case they are needed again. I don't consider this a valid issue.

**Comment by robske110** [comment]
512MB are just too less for 40players. I need 2-3GB for 20. Even vanilla PC servers cannot run 40players with 512MB ram.

**Comment by dktapps** [comment]
I don't understand what the problem is to be honest. If you allocate X amount of space, it makes no difference whatsoever what percentage of X space it uses to do stuff. Performance > using less memory, provided it doesn't exceed your set limit (which is what memory triggers are for).

PocketMine's memory usage isn't exaggerating. You're simply trying to ask it to do too much with not enough resources. Set a soft memory limit.

Especially since 1.0, chunk I/O _really really really_ hurts performance, so using a little more memory is preferable if it means that chunks don't need to be re-loaded.
