### ISSUE TITLE
In creative mode and spectator mode, flying slow after teleport

### ISSUE THREAD

**Issue by leolee3914** [pmmp/PocketMine-MP#3552]
### Issue description
In creative mode and spectator mode, flying slow after teleport

I have confirmed that it is caused by `Player->sendPosition() : $pk->onGround = $this->onGround;`
https://github.com/pmmp/PocketMine-MP/blob/92ed9e61256a3ba353202e29d05c42acdf9e9528/src/pocketmine/Player.php#L3755
When `$pk->onGround = true`, It will fly slowly

https://youtu.be/mTrgnd65etE

### Steps to reproduce the issue
1. /gamemode 1  or  /gamemode 3
2. Start flying (At this time, the sprinting speed is still normal)
3. /tp ~ ~ ~, After teleport, do not change the flying height
4. Try sprinting, It will fly slowly

### OS and versions

* PocketMine-MP: 3.12.4
* PHP: 7.3.12
* Server OS: Windows 10
* Game version: PE

### Plugins

- If you remove all plugins, does the issue still occur? YES

### Free Hong Kong, revolution now

**Comment by dktapps** [comment]
ladies and gentlemen, this is what happens when I break the sacred rule "don't trust people who say they tested their change".

caused by #3492

**Comment by dktapps** [comment]
While it seems that #3492 did indeed cause this bug, there's a few underlying bugs which are causing it to manifest in this way. If you switch to spectator mode while on ground to start with, flying will be affected by this same bug.
The core problem is the "on ground" state of entities not getting synced properly when its state changes, for example due to a teleport. For example, try teleporting a non-moving zombie 10 blocks into the air - you'll notice it sticks in the air and doesn't fall.
