### ISSUE TITLE
Master branch error: "Class 'pocketmine\timings\TimingsRecord' not found"

### ISSUE THREAD

**Issue by KingOfTurkey38** [pmmp/PocketMine-MP#3964]
### Issue description

- Expected result: What were you expecting to happen?
Server loads without crashing
- Actual result: What actually happened?
Server crashes on loading

### Steps to reproduce the issue
1. Make a fresh new pmmp server (PM4)
2. Start it

### OS and versions

* PocketMine-MP: 4.0.0+dev
* Phar built on the commit: d39348929f84eedbf99639a962ce9725611be9f1
* PHP: 7.4.12
* Server OS: PMMP

### Crashdump, backtrace or other files
It kept saying invalid crashdump when I was trying to post it in crashdumps so here's it:

PocketMine-MP Crash Dump Wed Dec 9 22:04:11 UTC 2020

Error: Class 'pocketmine\timings\TimingsRecord' not found
File: [pmsrc]/src/timings/TimingsHandler
Line: 94
Type: Error

THIS CRASH WAS CAUSED BY A PLUGIN

**Comment by dktapps** [comment]
I don't see any crashdump ...

The class clearly exists: https://github.com/pmmp/PocketMine-MP/blob/d39348929f84eedbf99639a962ce9725611be9f1/src/timings/TimingsRecord.php

and this is the first time I've heard of such an issue since this change was introduced (and all of my own servers are working correctly), so I conclude that this is a problem you've created for yourself somehow. As such, this is a support request.
