### ISSUE TITLE
Changing entities behavior

### ISSUE THREAD

**Issue by Govdim** [pmmp/PocketMine-MP#4006]
## Description
We have the ability to change and supplement the behavior of items and blocks using the plugin.

At the moment, API 4.0.0 has a problem with changing entities. Replacing the class in the EntityFactory will do nothing, since new entities are spawned directly through object creation, ignoring the content of the EntityFactory.

The new entity needs to be spawned using the saved names, as it was implemented in API 3.0.0

**Comment by dktapps** [comment]
This was intentionally removed. Plugins have no business touching save names or save data in any form, the same way they have no business touching block or item IDs.

In the majority of cases I've seen, use of custom entity classes has been a result of improper solving of XY problems (misuse of the API), or weakness / lack of functionality provided by the API.

That said, there are some (rare) cases where overriding classes is the only option (similarly to overriding player classes), but every time someone has asked for this feature back, their justification has never been valid.

I do plan to introduce a system to allow this functionality (which won't depend on entity save IDs), but right now it's low priority because nobody has given me a good reason why I should bring it back.
