### ISSUE TITLE
XBOX Rename Bug

### ISSUE THREAD

**Issue by Infernus101** [pmmp/PocketMine-MP#4042]
### Issue description
`player.verify-xuid` setting doesn't account for XBOX renaming. If a player with username X changes their username to Y and someone else changes their username to X, they wont be able to login since the XUID of X has now changed.
- Expected result: Successfully login
- Actual result: Unable to login

### Steps to reproduce the issue
1. Change username from X to Y and then with other account change username to X and try to join.

### OS and versions

* PocketMine-MP: 11630ab
* PHP: 7.3
* Server OS: Ubuntu
* Game version: PE/Win10

### Plugins

None
- If you remove all plugins, does the issue still occur? Yes
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

### Crashdump, backtrace or other files

None

**Comment by dktapps** [comment]
This is intended. Users shouldn't be able to hijack another player's data regardless of whether their name has been changed or not. That's the whole point of the setting.

**Comment by dktapps** [comment]
To be clear, the underlying system on PM3 is still using usernames to identify player data, because changing that at this point would break way too much stuff and that's not an option for a stable release line. It merely prevents different Xbox accounts which share a similar username from hijacking each others' data. It's not a great solution, but it's the least disruptive one I could come up with.
