### ISSUE TITLE
Players from 1.16.210 cannot connect to server.

### ISSUE THREAD

**Issue by BestCodrEver** [pmmp/PocketMine-MP#4064]
Please fix this, when players from 1.16.210 try to join, they get kicked and the prompt comes up saying “Outdated server”. Pls update pocketmine.

**Comment by mmm545** [comment]
be. patient. pls

**Comment by AkmalFairuz** [comment]
Close issue pls, you're not helping anything.

**Comment by supercrafter333** [comment]
PocketMine-MP will Updated soon. Please close your Issue.

**Comment by ethaniccc** [comment]
If you delete pocketmine and your server this issue won't occur !1!1!

**Comment by DragonfireHD** [comment]
@ethaniccc The person only asked kindly when the version was updated. You are exaggerating completely and not paying attention to your choice of words. You can just talk to this person in a civilized manner and not as if you had an animal in front of you. You yourself want to not that people talk to you like that these people use this plugin because they are on your side then talking to him like that is just disrespectful that is my opinion dazz
