### ISSUE TITLE
No Sound after 1.0.4 (e.g. Blocks Breaking, Walking, Pickups)

### ISSUE THREAD

**Issue by markkrueg** [pmmp/PocketMine-MP#415]
### Issue description
After 1.0.4, most sounds no longer occur in game. Examples:
Blocks Breaking
Walking
Picking Up Blocks

### Steps to reproduce the issue
1. Break a block; no sound
2. Pick up block you broke; no sound
3. Walk around; no sound

### OS and versions
* PocketMine-MP: PocketMine-MP 1.6.2dev 「Unleashed」 implementing API version 3.0.0-ALPHA4 for Minecraft: PE v1.0.4.11 (protocol version 102) (commit a717473)
* PHP: 7.0.14
* Server OS: Ubuntu Server 16.04.2 LTS
* Game version: Android 1.0.4

**Comment by markkrueg** [comment]
I wonder if this is an App bug. I'm surprised it's not being talked about more:

https://www.reddit.com/r/MCPE/comments/5yk1lh/windows_10_no_sound_effects/

This isn't Android, but seems like the same problem:

https://bugs.mojang.com/browse/MCPE-20289

Should I assume this is an application bug and close this?

**Comment by Muqsit** [comment]
dktapps tweeted about it though.
https://twitter.com/dktapps/status/840225707208896512

**Comment by robske110** [comment]
Found another interesting piece of the puzzle
>In both instances the Host of the world could hear just fine.
(Reference: https://bugs.mojang.com/browse/MCPE-20294)
It looks like either the protocol has changed and mojang forgot to adopt its own client to it, or mojang simply introduced a bug in their client, so that it will no longer respond or play sounds sent from servers.

**Comment by HimbeersaftLP** [comment]
> It looks like either the protocol has changed and mojang forgot to adopt its own client

Would not be the first time xD

> or mojang simply introduced a bug

Mojang introducing a bug:
"And today, we present you, MCPE 1.0.4, now with even more bugs!!"
***Applause from the audience***

**Comment by markkrueg** [comment]
Based on the followup to dktapps tweet referenced by Muqsit above; it seems like this has been fixed in api3/network branch.

**Comment by dktapps** [comment]
This is not a client issue, but due to an alteration in the behaviour of resource packs in 1.0.4. Since they now control sounds also, the initial resource pack exchange must be completed correctly in order for sounds to work. The master branch does not currently do this.

**Comment by Dakor91** [comment]
@markkrueg you can remove or comment out Line 434 of the https://github.com/pmmp/PocketMine-MP/blob/api3/network/src/pocketmine/PocketMine.php `"openssl" => "OpenSSL", ` and it will run with sound with the current php package 👍

**Comment by dktapps** [comment]
... and will crash if you try to use resource packs. Please do not encourage hacking.

**Comment by Muqsit** [comment]
It's really simple to compile with OpenSSL. There are php-build-scripts repos dedicated for this cause on GitHub.

**Comment by Sandertv** [comment]
I did some testing to see if it actually worked without OpenSSL, which it did. It didn't crash, give any errors or any other weird behaviour. There's two weird things I came by when doing so, but I don't know if is because of missing OpenSSL or not. Anyways, here they are:

Loading screen displays unexplicable images:
![screenshot_2017-03-12-20-21-26](https://cloud.githubusercontent.com/assets/16114089/23835055/ca5aabd4-0760-11e7-89ec-1d630692600b.png)

Retextured health and Food bar show wrong textures:
![screenshot_2017-03-12-20-30-44](https://cloud.githubusercontent.com/assets/16114089/23835069/fdacaaf0-0760-11e7-9de0-e58569c87e29.png)

I did experience the second issue without the server forcing texture packs before however, and a simple MCPE restart did the job. This is not the case here though.

Apologizes if those were because of OpenSSL missing, I'm just too lazy to install it at the moment, and just wanted to test it.

**Comment by dktapps** [comment]
OpenSSL is required for resource-pack hashing, it will crash if you attempt to have the client download packs without it.

**Comment by Sandertv** [comment]
That is very odd. It said that OpenSSL was missing yet I did not experience any issues with the crashes.

**Comment by dktapps** [comment]
@Sandertv your issue is here: https://bugs.mojang.com/browse/MCPE-20369

**Comment by Sandertv** [comment]
Yeah I reported that. Sorry for reporting it here, I realized it has to be a client issue when it occured on single player too.

**Comment by markkrueg** [comment]
I would just like to confirm that sound is working fine using the api3/network branch with OpenSSL.

**Comment by kaitododoyt** [comment]
Error in compiled Phar api3/network

[09:21:25] [Server thread/CRITICAL]: Unable to find the OpenSSL (openssl) extension.
[09:21:25] [Server thread/CRITICAL]: Please use the installer provided on the homepage, or recompile PHP again.

Anyone know why? I can use without compile

**Comment by dktapps** [comment]
maybe if you read what it's telling you... OpenSSL is a required extension for certain new core features.

**Comment by kaitododoyt** [comment]
sorry, yes its obviously, but i dont know where to look and add this. can you tell me?, and thanks for the 1.0.5 branch, is really awesome
