### ISSUE TITLE
People being able to edit sign text after it being replaced

### ISSUE THREAD

**Issue by UnknownOre** [pmmp/PocketMine-MP#4198]
### Issue description

- Expected result: Player not being able to change Sign Text if the block is replaced
- Actual result: Player being able to replace the text

### Steps to reproduce the issue
1. Place a Sign
2. have some code that cancel block break event
3. break the old sign and place a new sign really fast
4. voila you can edit the text now

### OS and versions

* PocketMine-MP: 3.18.0
* PHP: 7.4
* Server OS: Ubuntu

**Comment by dktapps** [comment]
This has been a long standing issue for many years because there is no reliable way to determine when the text has finished being edited. The client continuously sends text updates while it's typing, and doesn't tell when the sign edit UI is closed.

**Comment by dktapps** [comment]
If you're writing a protection plugin, you should consider cancelling SignChangeEvent in addition to the other events.

**Comment by dktapps** [comment]
For posterity: It's been suggested to limit sign modification to the person who originally created the sign, which would eliminate almost all of the problems for spawn protection.

This was previously done in the Shoghi days, but was removed due to timing issues causing signs to go blank. It would be better to permanently tag signs with the creator ID, which would allow the creator to always edit the sign (not really a problem), but prevent anyone else from doing the same.
