### ISSUE TITLE
Client cannot join to server.

### ISSUE THREAD

**Issue by OguzhanUmutlu** [pmmp/PocketMine-MP#4219]
### Issue description

- Expected result: Player should be able to join the server.
- Actual result: Client sends a packet named PacketViolationWarningPacket and this packet's information is: type: 0, severity: 2, packetId: 7, message: ""
- The packet that causes this error's dump(ResourcePackClientResponsePacket):
``object(pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket)#85938 (8) {
  ["status"]=>
  int(3)
  ["packIds"]=>
  array(0) {
  }
  ["isEncoded"]=>
  bool(false)
  ["__encapsulatedPacket"]=>
  NULL
  ["senderSubId"]=>
  int(0)
  ["recipientSubId"]=>
  int(0)
  ["offset"]=>
  int(4)
  ["buffer"]=>
  string(8) "08030000"
}``

### OS and versions
* PocketMine-MP: PocketMine-MP 3.19.1
* PHP: 7.4
* Server OS: Windows
* Game version: PE/Win10

### Plugins
A plugin that changes LoginPacket's protocol and clientData["PlayFabId"] properties to let 1.16.20/1.16.40 players to join 1.16.220.
Note: I know they don't support multi protocol but i'm trying to do it.

### Crashdump, backtrace or other files
Nothing.

**Comment by ethaniccc** [comment]
Wow, it's almost as if it's the fault of your plugin!

Let's learn what PacketViolationWarningPacket is:
https://github.com/Sandertv/gophertunnel/blob/master/minecraft/protocol/packet/packet_violation_warning.go#L17

So basically, what this means, is that the server is sending bad information to the client - the older client don't know how to process newer protocol (which is why they're blocked in the first place). If you're not translating packets, your plugin is just as good as the old `LoginPacket->protocol = current`

**Comment by OguzhanUmutlu** [comment]
So, what should i do?
