### ISSUE TITLE
When cancelling EntityDamageEvent, EntityDamageByEntityEvent is still handled

### ISSUE THREAD

**Issue by Prim69** [pmmp/PocketMine-MP#4281]
### Issue description

- Expected result: EntityDamageByEntityEvent to not be handled
- Actual result: It was called

### Steps to reproduce the issue
1. cancel EntityDamageEvent
2. Attack an entity and log something in EntityDamageByEntityEvent

### OS and versions

* PocketMine-MP: 4.0.0
* PHP: 8.0.7
* Server OS: Windows 10
* Game version: Win10

### Plugins
 Plugins (2): Core v3.2.0, DevTools v1.15.0+dev

- If you remove all plugins, does the issue still occur?
   No
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

    public function onDamage(EntityDamageEvent $event) : void {
    	       $event->cancel();
    }

    public function onDamageByEntity(EntityDamageByEntityEvent $event) : void {
    	       var_dump('called');
    }

**Comment by dktapps** [comment]
Both handlers are receiving the same event instance. The EntityDamageByEntityEvent handler is called first, and then the less specific handler (EntityDamageEvent) later. Therefore this is expected behaviour.

That said, there is no defined order in which these handlers will execute, so you shouldn't depend on this behaviour.

**Comment by SOF3** [comment]
If you need one handler to be executed before another, you should use the `@priority` attribute.
