### ISSUE TITLE
Chat sent by players will be translated

### ISSUE THREAD

**Issue by Nerahikada** [pmmp/PocketMine-MP#4371]
### Issue description

- Expected result: What were you expecting to happen?
Messages sent by the player will be displayed as they are.
- Actual result: What actually happened?
Messages that contain translations will be translated and displayed.

### Steps to reproduce the issue
1. Send chat "%language.name".
2. It will display "English" instead of "%language.name"

### OS and versions

* PocketMine-MP: 4.0.0+dev
* PHP: 8.0.9
* Using JIT: no 
* Server OS: Windows
* Game version: Win10

### Plugins

```
[20:54:40.541] [Server thread/INFO]: Plugins (0):
```
- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by dktapps** [comment]
I guess this happens because of this code: https://github.com/pmmp/PocketMine-MP/blob/789a669395a0d4d9e2ca59b3244e41f3ff05b5b3/src/player/Player.php#L1781

There are still some things implicitly depending on this translation behaviour, such as HelpCommand, which embeds untranslated translation keys into raw messages. Until these cases are fixed, this issue will remain.

**Comment by dktapps** [comment]
Fixed by https://github.com/pmmp/PocketMine-MP/commit/5da90b9530c4100cd7c3971675faea74f27b5438 (and the preceding commits).
