### ISSUE TITLE
Some messages do not send the usual translation results to the client

### ISSUE THREAD

**Issue by Rush2929** [pmmp/PocketMine-MP#4379]
### Issue description

- Expected result: The server will tell the client that the command was not found, depending on the locale.
- Actual result: The server will send "commands.generic.notFound" to the client. However, in the case of the console, it will send the translated message.

### Steps to reproduce the issue
1. execute /undefined

### OS and versions

* PocketMine-MP: b3298d7
* PHP: 8.0.9
* Using JIT: no
* Server OS: Ubuntu 20.04
* Game version: Android/Win10

### Plugins

Plugins (0):

### Crashdump, backtrace or other files

![Minecraft 2021_08_17 午後 11_48_00](https://user-images.githubusercontent.com/76860328/129759214-f917e29d-dccc-4065-b969-81d7de609298.png)
<img width="932" alt="!" src="https://user-images.githubusercontent.com/76860328/129760602-032d1540-0fd4-48f9-b853-447a4c11e3b1.png">

**Comment by dktapps** [comment]
This happens because the server doesn't translate strings sent to the client unless the translation key begins with `pocketmine.`, because it allows vanilla translations to be used. However, this becomes a problem if the vanilla translations corresponding to those keys get removed, as appears to have happened in this case.

The appropriate solution would be to replace `commands.generic.usage` with a more specific `pocketmine.commands.generic.usage`, which would always be translated by the server. In addition, this would allow more flexibility than the current translation allows (e.g. showing the command name instead of just saying "unknown command").

**Comment by thebigsmileXD** [comment]
I would suggest checking if vanilla has the specified translation string, but i am not sure how the vanilla resources may be shared, license wise.  Optionally one could ask the user to apply a vanilla pack on the server, and load the translations from there. Might be a task for a plugin.

PM would get the string from the translation file, but players receive the translation key instead.
