### ISSUE TITLE
NoClip after swimming

### ISSUE THREAD

**Issue by SandhyR** [pmmp/PocketMine-MP#4753]
### Issue description

- Expected result: Player obstructed by block
- Actual result: Player not obstructed by block

### Steps to reproduce the issue
1. Swimming
2. Walk on the block as high as 2 blocks

### OS and versions
* PocketMine-MP: 4.1.0-BETA1
* PHP: 8.0.13
* Using JIT: no
* Server OS: Linux
* Game version: Linux unofficial launcher (Android)

### Plugins
none

Video demonstration: https://youtu.be/NBJWM9VKW2Y

**Comment by dktapps** [comment]
Yeah, I'm aware of this. Previous investigation suggests it's a client bug which doesn't happen in vanilla due to lucky coincidence.

What's actually happening is the player retains the 0.6x0.6 collision box they had while swimming on the client side. PM attempts to reset it, but the reset doesn't take for some reason.

**Comment by dktapps** [comment]
Fixed by d9ea6479258277bd71138f70b0aac0ea4fc99614.
