### ISSUE TITLE
[Bug] Minecraft crash by itemid 358:0

### ISSUE THREAD

**Issue by Bubbelwubbel** [pmmp/PocketMine-MP#4792]
### Issue description

- That this item works.
- As soon as I use this item, my Minecraft crashes immediately. My Minecraft also crashes when entering the server because of the item.

### Steps to reproduce the issue
1. Join the server
2. Give you the item with the ID: 358:0
3. Grab this item and your Minecraft will crash.

### OS and versions
* PocketMine-MP: 4.1.0-BETA1 (git hash: 587da478a69ef89fe22b97ffb1b151bdf6220b7c)
* PHP: 8.0.12
* Using JIT: disabled
* Server OS: Windows11
* Game version: Android/iOS/Win10/Xbox/PS4/Switch

### Plugins
BedWars v0.0.2-Beta, BuilderTools v1.4.0-dev, DevTools v1.15.0+dev, GameAPI v1.0.1, MultiWorld v1.7.0-beta4 [BedWars & GameAPI are my plugins]

- If you remove all plugins, does the issue still occur?
    yes

### Crashdump, backtrace or other files
Nothing available.

**Comment by dktapps** [comment]
This is a bug in the client.

**Comment by PocketMiner92** [comment]
Client Bug?
Xd
This is the ID of a filled Map and need a Data.
Pocketmine havent Maps implemented.
This is also a Bug by Pocketmine and not a Client Bug.

**Comment by ColinHDev** [comment]
Why should a client crash just because the item has no data.
Although it might not be intentional that a map without data exists normally, it could come through corrupted data or any of the many bugs of the game. You can delete your world if that would happen in single player.

**Comment by PocketMiner92** [comment]
This is Dylan
All Bugs are Client Bugs.
🤣🤣🤣🤣

**Comment by ColinHDev** [comment]
> Why should a client crash just because the item has no data.
> Although it might not be intentional that a map without data exists normally, it could come through corrupted data or any of the many bugs of the game. You can delete your world if that would happen in single player.

I literally agreed that this is a client bug and not one of pmmp

**Comment by PocketMiner92** [comment]
Nope its a Pocketmine Bug
You can Test it in Powernukkit too.
But you can join in Powernukkit after the Client close the Session.
In normal Nukkit too 
A Map without Data is a Map without Data.

**Comment by dktapps** [comment]
The game is not supposed to crash on weird server data. That's a client bug.

In the same way that the server is not supposed to crash if the client sent it weird data.

**Comment by PocketMiner92** [comment]
In Pocketmine, you cant join the Server as Long this item is in youre Inventory

**Comment by dktapps** [comment]
I'm aware, but since this doesn't happen unless you intentionally did it to yourself, it's not my concern. This didn't used to crash the client.

Other servers that have "fixed" this have simply worked around the problem.

**Comment by PocketMiner92** [comment]
I cant hear this Shit Not longer xd
A Missing Item and his Functions is a Client Bug.
I cant believe it. 🤣🤣🤣🤣

**Comment by dktapps** [comment]
That's not what I said.

**Comment by dktapps** [comment]
For posterity, the reason for this crash is because the NBT is not populated. If you inventory-edited a vanilla world and gave yourself this item without any NBT tags, the same exact crash would happen, and you wouldn't be able to open the world. This could legitimately happen if the world save was damaged for some reason, but you don't expect that the game will crash when loading a vanilla world in single player.

Therefore this is a problem that needs to be fixed by Mojang. I could work around it, but it doesn't make sense to because it's not my bug and the impact of this is basically zero anyway - you have to give yourself this crashy item on purpose in order for it to cause a problem.

**Comment by PocketMiner92** [comment]
I have linked this answer in Mojangs Bug Report.

**Comment by dktapps** [comment]
A link to the bug report would be appreciated.

**Comment by PocketMiner92** [comment]
What do you Hope from Mojang?

An answer that this Map isnt supported by Pocketmine?
Mojang and Pocketmine?
You have marked many Issues as (Client) Bug.
And next day it was fixed.
Great Client Bug 
Try to implement Maps and it works without Any crashs.
Without useless (Workarounds)
But this is youre Problem!
You say thousands of Times.
Halleluja, Pocketmine cant implement this because i have no time Blabla.
Each Block, is handled by Plugins.
You should try youre best and implement Blocks and Items by yourself and Not with hundets of Plugins.
It works fine.
