### ISSUE TITLE
Chunks flash when sprinting in spectator (1.19.0)

### ISSUE THREAD

**Issue by AntonPPDS** [pmmp/PocketMine-MP#5105]
### Issue description

- Expected result: chunks not flashing in spectator
- Actual result: chunks flashing

### Steps to reproduce the issue
1. Set your gamemode to spectator
2. Switch between sprinting and walking frequently (or any other action that updates generic flags, e.g. sneaking)
3. You will see that chunks are flashing.

### OS and versions
* PocketMine-MP: 4.5.1
* Game version: Win10

### Plugins
No plugins

### Demonstration recording
<details>

https://user-images.githubusercontent.com/60366294/172787219-adb1680d-86d7-4ded-b394-b6a4c0484642.mp4

</details>

<br>
There is already a PR #5103 that fixes this, but for some reason it's closed.

**Comment by dktapps** [comment]
The PR doesn't fix anything, as I already said. That change fixes the flashing in native spectator (gamemode 6) but not PM spectator (which uses creative + some adventure settings flags). I don't plan on changing to gamemode 6 due to it being incomplete.

This is a bug in the client whose cause I'm currently unaware of and don't plan on devoting the resources to fix. You're welcome to investigate it yourself.

**Comment by AntonPPDS** [comment]
I don't know why it didn't work for you, but I personally tested this PR and it actually fixed the flashing for me. There are no additional modifications in the core and no plugins. Perhaps this is due to the OS where the game is installed? Where did you test it that didn't work for you?

**Comment by dktapps** [comment]
Windows. Try flying up and down.

**Comment by AntonPPDS** [comment]
Windows too. Everything is OK using fix from PR.
<details>

https://user-images.githubusercontent.com/60366294/172842956-233816e1-df50-4fe5-ad0f-a4480c0f182f.mp4


</details>

**Comment by dktapps** [comment]
Your video doesn't load, but I tested it a second time. It looks like there must have been some error in my testing methodology. However, the PR'd fix isn't correct because the bug isn't exclusive to spectator mode, but rather any place where noclip is used (which can include setHasBlockCollision(false) since 4.1).

**Comment by dktapps** [comment]
Fixed by bb5b52d99882b15fc950d79da2084312df173bdb.
