### ISSUE TITLE
Default world

### ISSUE THREAD

**Issue by SunsetTadpole78** [pmmp/PocketMine-MP#5166]
## Description
add a function in the World.php file to know if the world is the default world or not

## Justification
This will make it possible to no longer do code like:
```php
if($player->getWorld()->getDisplayName() == $worldManager->getDefaultWorld()->getDisplayName()) {
    //Code
}
```
but rather:
```php
if($player->getWorld()->isDefault()) {
    //Code
}
```

We could therefore add a `, $isDefault` to this line in the WorldManager after the AsyncPool: 
https://github.com/pmmp/PocketMine-MP/blob/2b61c025c26394c3293bcc12a2d0b2301cb4c7ee/src/world/WorldManager.php#L246
and this line:
https://github.com/pmmp/PocketMine-MP/blob/2b61c025c26394c3293bcc12a2d0b2301cb4c7ee/src/world/WorldManager.php#L271

**Comment by ColinHDev** [comment]
I just want to mention that you don't need to compare the world's name, especially since the display name may not be unique for each world, unlike the folder name. (Also `getDefaultWorld()` can return null, which you would have to address in your code as well, at least by using the null coalescing operator `getDefaultWorld()?->getDisplayName()`)
It is sufficient to compare if both objects are the same. 
```php
if ($player->getWorld() === $player->getServer()->getWorldManager()->getDefaultWorld()) {
    ...
}
```

**Comment by dktapps** [comment]
I don't really see the point of this. An API break for a benefit this irrelevant doesn't seem justified.
