### ISSUE TITLE
Value exceeds the range

### ISSUE THREAD

**Issue by Misteboss** [pmmp/PocketMine-MP#518]
### Issue description
When I try to remove effect from a player who don't have one i have this message in the console
[17:05:12] [Server thread/CRITICAL]: InvalidArgumentException: "Value -4 exceeds the range!" (EXCEPTION) in "/src/pocketmine/entity/Attribute" at line 175

### Steps to reproduce the issue

1. ... Remove effect from a player who doesn't have one
2. ... Check the console

### OS and versions
* PocketMine-MP: Last commit of api3/network
* PHP: 7.0.2
* Server OS: Debian
* Game version: PE/Win10 

### Crashdump, backtrace or other files

* ...  https://thimbleprojects.org/misteboss/245098/particule.html

**Comment by dktapps** [comment]
As per [this](https://forums.pmmp.io/threads/why-my-task-crash-doesnt-work.1690/#post-18254) post, I deduced an issue with absorption.

Steps to reproduce without plugins
- /effect dktapps absorption 600 0
- /tp ~ ~20 ~ (or any other thing to lose some absorption points)
- /effect dktapps clear -> error in console

It seems I forgot that the absorption attribute can change while absorption is in use. The code therefore attempts to remove a full 4 absorption points when the player has lost all their absorption points due to absorbing damage.
