### ISSUE TITLE
Raklib block IP on join (0.16)

### ISSUE THREAD

**Issue by Misteboss** [pmmp/PocketMine-MP#52]
### Issue description

When a player join raklib blocked automatically the IP and the player can't join
### Steps to reproduce the issue

1. ... Use 0.16 version of PM
2. ... Join the server

### OS and versions

* PocketMine-MP: d763cb
* PHP: 7.0.2
* Server OS: Debian 8
* Game version: PE/Win10 0.16(delete as appropriate)

### Crashdump, backtrace or other files

* ...
<img width="690" alt="capture d ecran 2016-10-25 a 22 09 16" src="https://cloud.githubusercontent.com/assets/17687222/19702407/cd7cb7da-9aff-11e6-8d7d-1f63fe7ba390.png">

**Comment by dktapps** [comment]
Not supported. Closing.

**Comment by Misteboss** [comment]
@dktapps I know it's not supported but check that cause for the moment pocketmine 0.16 doesnt work.

**Comment by Misteboss** [comment]
just check @dktapps. it's your work.

**Comment by dktapps** [comment]
A 0.15 player attempted to join your server. Because of protocol changes between 0.15 and 0.16, older versions cannot be automatically detected, and this causes assertion errors internally.

Make sure zend.assertions is set to 0 or -1 in your php.ini, as 1 will cause this to occur. Assertions are for debug only. Without assertion, old players will simply timeout.
