### ISSUE TITLE
Why is /me still a command!

### ISSUE THREAD

**Issue by Lazerplayz** [pmmp/PocketMine-MP#522]
Why is /me even needed all of the MC:PE servers block the command anyway it's really useless for servers!

**Comment by mhsjlw** [comment]
It is a vanilla command

**Comment by Lazerplayz** [comment]
It's useless

**Comment by mhsjlw** [comment]
> use·less
ˈyo͞osləs/Submit
adjective
not fulfilling or not expected to achieve the intended purpose or desired outcome.

It does fulfill its purpose, it prints out your name and your message.

**Comment by madecode15** [comment]
@Lazerplayz 

Why do people use the issue tracker as a discussion form?

To answer your question, as "useless" as you think it is, PocketMine-MP is a 100% vanilla server software. Meaning, if it is in vanilla PocketMine-MP will implement it. We have plugins to control what we don't want or extend features. Don't like /me? Block it with a plugin. Otherwise many people who don't host large game servers may like it.

**Comment by MCPEGamerJPatGitHub** [comment]
@Lazerplayz your comments are too dumb

**Comment by Muqsit** [comment]
Shoghi structured it the same way bukkit did their server. Commands included.

**Comment by SOF3** [comment]
Please use the forums for controversial discussion.

**Comment by SOF3** [comment]
@Lazerplayz @MCPEGamerJPatGitHub 
Please use the forums for controversial primarily-opinion-based discussion.
Discussion involving personal attack is especially disallowed.
Please keep the issue tracker clean of any subjective comments.
