### ISSUE TITLE
It is not possible to dye leather armor in cauldrons.

### ISSUE THREAD

**Issue by IvanCraft623** [pmmp/PocketMine-MP#5220]
### Issue description
Although the code for dyeing these armors is present, when attempting to dye, only the amount of water in the cauldron is reduced and the armor is not dyed.

- Expected result: What were you expecting to happen?
Have a dyed armor
- Actual result: What actually happened?
There is no dyed armor

### Steps to reproduce the issue
1. Place a cauldron
2. Fill it with water
3. Dye the cauldron
3. Right click the cauldron with a leather armor

### OS and versions

* PocketMine-MP: 5.0.0-ALPHA3 723ae9eca08dd74e1706b4d02e964b9c6c086cd1
* Server OS: Linux

**Comment by dktapps** [comment]
This is caused by the following code:
https://github.com/pmmp/PocketMine-MP/blob/next-major/src/player/Player.php#L1462

While this works well for handling stuff like decrementing item counts or damaging tools, it also prevents any other modifications to the held item from taking place, like this one. It would seem that the logic for deciding whether or not to replace the held item needs to be more specific.
