### ISSUE TITLE
Super slow growth

### ISSUE THREAD

**Issue by max-xoo** [pmmp/PocketMine-MP#5409]
### Issue description

- Expected result: That the shoots grow at the same speed as pm3 (because this bug is not on pm3)

- Actual result: The more players are connected to the server, the more chunks are loaded and the slower the shoots will be (if there are 100 players it can take 50 minutes for a shoot to go from one stage to another)

### Steps to reproduce the issue
1. Make a farm
2. Wait for a seed to grow

### OS and versions

* PocketMine-MP: 4.10.0
* Using JIT: no
* Server OS: Ubuntu 20.10
* Game version: Win10

### Plugins

- If you remove all plugins, does the issue still occur? Yes

### Crashdump, backtrace or other files

- https://youtu.be/HIQPfQ719aU Crops growth 
- https://timings.pmmp.io/?id=244916 timings during the growth
- [Screenshot](https://cdn.discordapp.com/attachments/373199722573201410/1036015039745884240/unknown.png) after 51 minutes of afk (continuity of the video above)

**Comment by dadodasyra** [comment]
Seems like it's true, I have the same problem, it's really slow as f.
But i'm not 100% sure it's related to how many players are connected.

The issue is same with 20 players~, it takes really long time to grows.
Here's my timings https://timings.pmmp.io/?id=245434

**Comment by dktapps** [comment]
Please send your pocketmine.yml

**Comment by max-xoo** [comment]
> Please send your pocketmine.yml

https://pastebin.com/x5grS10n

**Comment by dadodasyra** [comment]
https://pastebin.com/7NFfC2nb for me

**Comment by dktapps** [comment]
I'm not able to reproduce this using a fresh pocketmine.yml using melon seeds (as per the video).

**Comment by max-xoo** [comment]
How many chunks are loaded? The more chunks are loaded the longer it takes to push (but it increases the time very very fast and it increases a lot)

**Comment by dktapps** [comment]
I think this is almost entirely influenced by player count, not by chunks loaded. You can see here that the default simulation radius is 3 chunks: https://github.com/pmmp/PocketMine-MP/blob/732dac6fc147087c2acf8f60d1a2db5bfc7243a6/resources/pocketmine.yml#L125

This means that it doesn't matter how big your radius is, only how many players there are, since no one has a render distance of less than 3.

The most influential setting in this case is going to be this one: https://github.com/pmmp/PocketMine-MP/blob/732dac6fc147087c2acf8f60d1a2db5bfc7243a6/resources/pocketmine.yml#L123

This value gets divided between all the online players. If the players are clustered in a small area, this is fine, but if they are widely distributed, chunk ticking with 100 players will be only 2.5% of the speed of what it would be with a single player.

This is the same logic as in PM3, so there shouldn't be any difference unless you were already using a customised configuration for this setting in PM3.

**Comment by enrik0308** [comment]
Yes I confirm the issue wasn't here on PM3

**Comment by dadodasyra** [comment]
Same, I was using servers with like 80 players with probably the same config on PM3 and it was not so slow. The thing is that even with 20 players everyone is complaining about it. There's probably something more that this per tick value, or it wasnt working correctly well on PM3.
Trust me I can assure you it was not like this before. But I can't really tell you what changed between..

**Comment by dktapps** [comment]
The only thing that changed is retention of `chunkTickList` (removed), and that was disabled on PM3 by default anyway. You'd have to go out of your way to enable it.

**Comment by dktapps** [comment]
If you're up for the risk, you can try the latest `next-minor` commits. It should be better there.

**Comment by dktapps** [comment]
Can anyone report whether 4.11.0-BETA2 improves on this?

**Comment by max-xoo** [comment]
My servers are closed so I can't.

**Comment by dadodasyra** [comment]
I installed it on my server and.. this is... really bad.
In fact crops are growing normally but this has a HUGE performance impact
Here's a timings https://timings.pmmp.io/?id=245596

**Comment by dktapps** [comment]
That's pretty much what I expected. The old code only escapes performance impact by massively slowing down growth and not working properly. The new code mimics vanilla.

In fact the timings report looks pretty good to me. 27% tick time spent on block ticking is quite acceptable IMO.

**Comment by dadodasyra** [comment]
Eww my bad I thought this was 100% caused by the beta but I have pretty same issue on other servers with the same worlds, the thing is that I really don't understand from where it come. Will continue this discussion on discussion, this issue is not for this and I guess I can't open an issue on this because it lacks of information and is more a support request that an issue.
Here's a server without the beta https://timings.pmmp.io/?id=245601

**Comment by dktapps** [comment]
Yes, I noticed that. Your scheduled block updates issue is probably unrelated to the beta.

That being said, some increase in CPU is to be expected with the new changes, since it's actually working correctly now.

**Comment by dadodasyra** [comment]
https://timings.pmmp.io/?id=245814 In fact you need to consider "faction1 - Random Chunk Updates", "faction1 - Random Chunk Updates - Chunk Selection" and

**Comment by dktapps** [comment]
As I said, this is entirely expected.

**Comment by ShockedPlot7560** [comment]
After many tests, this problem does not exist anymore with the last update.  
The speed of growth has returned to normal.
