### ISSUE TITLE
 Why "final" key for the IronOre class or for GoldOre for example?

### ISSUE THREAD

**Issue by Pab450** [pmmp/PocketMine-MP#5426]
### I wanted to modify the iron ore to drop an emerald.

As we know, the "final" keyword blocks the possibility to override these block classes to rewrite their operation.

In this case, let's take the example of the IronOre class. Since I can't extend this class I have to create a new one and i go call it IronOre2. Here is what my new class looks like:

```php
final class IronOre2 extends Opaque{

    public function getDropsForCompatibleTool(Item $item) : array{
        return [VanillaItems::EMERALD()];
    }

    public function isAffectedBySilkTouch() : bool{ return true; }
}
```

it's finally the same class just I changed the dropped item by an emerald!
then it is necessary to record this block which I do with this line: 

```php
BlockFactory::getInstance()->register(new IronOre2(new BlockIdentifier(BlockTypeIds::IRON_ORE), "Iron Ore", new BlockTypeInfo(BlockBreakInfo::instant())), true);
```

I start the server, everything is fine, I connect and the server crashes!

I get this errors: 
- `Value 6148914691165209940 is outside the allowed range -2147483648 - 2147483647 in IntegerishTagTrait`
- `No serializer registered for path\to\IronOre2 with type ID 10306 in BlockObjectToStateSerializer`
-  `No serializer registered for path\to\IronOre2 with type ID 10306" in ItemSerializer`

I put these lines after to try to solve the problem but it seems to me a little shaky:

```php
 GlobalBlockStateHandlers::getSerializer()->mapSimple($block, $id);
 GlobalItemDataHandlers::getSerializer()->map($block->asItem(), fn() => new SavedItemData($block->asItem()->getName()));
```

$block contains the IronOre2 instance and $id contains the BlockTypeId of the IronOre2 instance.

I then get another error: `Registering the same block twice! in BlockObjectToStateSerializer`

I stopped here because my brain was too hot. Maybe my code is wrong because I didn't understand how the whole thing works. 

**But I don't understand why some of these classes are final? it makes things tricky without much reason no?**

## PocketMine-MP info
This server is running PocketMine-MP
Server version: 5.0.0-ALPHA5 (git hash: 90305a0b9278f3d661c243c8b27d9748c567ae57)
Compatible Minecraft version: 1.19.40 (protocol version: 557)
PHP version: 8.0.24
PHP JIT: disabled
Operating system: mac

**Comment by dktapps** [comment]
You can do this using BlockBreakEvent->setDrops() without being a noisy neighbour for other plugins. I don't consider this a valid use case.

**Comment by Pab450** [comment]
> You can do this using BlockBreakEvent->setDrops() without being a noisy neighbour for other plugins. I don't consider this a valid use case.

BlockBreakEvent->setDrops() doesn't seem to me to be very adequate... why these classes include the term final? it's quite strange since other classes like DiamondOre don't include this keyword? 

So there is no other solution? on some class I understand the use of this keyword but here I don't see the point of it? this is not a negative remark, I would just like to know your point of view on this if you have some time to spare.

**Comment by dktapps** [comment]
Those classes are older. All newer classes are final by default due to code style rules, and in this case there isn't a good reason for them not to be final.

Final classes are advantageous for API design because they prevent inheritance of things that weren't designed to be inherited. Having to take inheritance into account severely limits the range of things that can be changed without BC breaks.

Technically speaking, in a non-final class, adding any new protected or public method, property or constant is a BC break because it can conflict with third party inheritors. PM currently ignores this problem in minor versions (except in cases where it could cause major breaks), but it means that API compatibility can't be semantically guaranteed according to the versioning scheme and has to rely on fuzzy human guesswork.

Finally, making a final class non-final is non-BC-breaking, but the other way around breaks user code.
