### ISSUE TITLE
BlockBreakEvent occasionally runs before PlayerInteractEvent

### ISSUE THREAD

**Issue by Joshy3282** [pmmp/PocketMine-MP#5490]
### Issue description

- Expected result: PlayerInteractEvent (start of break) is run before BlockBreakEvent (end of break)
- Actual result: BlockBreakEvent is occasionally run before PlayerInteractEvent for the same acting while instant mining blocks.

### Steps to reproduce the issue
1. Call PlayerInteractEvent and BlockBreakEvent
2. adding any type of print statement to both shows that they are not always called in proper order.

### OS and versions
* PocketMine-MP:  4.12.4
* PHP: 8.0.13
* Using JIT: no 
* Server OS: linux

![image](https://user-images.githubusercontent.com/67878880/210464738-5d8029ce-729a-42c2-aa52-60dac0f82246.png)

**Comment by dktapps** [comment]
The most likely explanation for this is that the `PlayerBlockAction` which triggers `PlayerInteractEvent` arrives in the same packet as the transaction which breaks the block. The transaction is currently processed before the block action in the handler, which would explain why this problem is occurring.
