### ISSUE TITLE
No deserializer found for blocks that are definitely registered

### ISSUE THREAD

**Issue by IvanCraft623** [pmmp/PocketMine-MP#5518]
### Issue description

As title.

### Steps to reproduce the issue

You can reproduce this with the following code:
```php
foreach ([BlockTypeNames::CRYING_OBSIDIAN, BlockTypeNames::DIAMOND_BLOCK, BlockTypeNames::GILDED_BLACKSTONE] as $typeName) {
	try{
		$item = GlobalItemDataHandlers::getDeserializer()->deserializeStack(GlobalItemDataHandlers::getUpgrader()->upgradeItemTypeDataString(
			$typeName,
			0, //meta
			1, //count
			null //nbt
		));
		$this->getLogger()->info("Successfully deserialized: " . $item->getName());
	}catch(ItemTypeDeserializeException $e){
		$this->getLogger()->error($e->getMessage());
	}
}
```

Output:
```
[Server thread/ERROR]: [Test] No deserializer found for ID minecraft:crying_obsidian
[Server thread/INFO]: [Test] Correctly deserialized: Diamond Block
[Server thread/ERROR]: [Test] No deserializer found for ID minecraft:gilded_blackstone
```

### OS and versions
* PocketMine-MP: 5.0.0-ALPHA6
* PHP: 8.0.24
* Using JIT: no
* Server OS: win

**Comment by dktapps** [comment]
These blocks didn't exist prior to 1.13, so they aren't recognized by the BlockDataUpgrader as an ID/meta pair. This is entirely expected behaviour.

You'll need to register your own upgrader mappings for this if you want it to work, since PM doesn't have any way to know what blockstate you expect the meta values to convert into.
