### ISSUE TITLE
Players don't tick chunks that come back in simulation distance if they never left the player's view distance

### ISSUE THREAD

**Issue by kenzeve** [pmmp/PocketMine-MP#5699]
### Issue description

Entity stops to tick normally after I fly away and then come back (but ticks when I stay very close to it)

### Steps to reproduce the issue
I used this code which spawns a villager to track ticks:
```php
$entity = new class($location) extends Villager{
            public function entityBaseTick(int $tickDiff = 1): bool{
                Server::getInstance()->broadcastMessage("tick");
                return parent::entityBaseTick($tickDiff);
            }
};
$entity->spawnToAll();
```

Then I fly away and come back after a while, and after that entity stops to tick normally.

Reproduced on 5.0.0-BETA2 and 4.19.0, not reproducable on 4.18.x

### OS and versions

* PocketMine-MP: 5.0.0-BETA2 / 4.19.0
* PHP: 8.2.4
* Using JIT: no
* Server OS: Win11
* Game version: Win11

### Crashdump, backtrace or other files

Video: https://youtu.be/v2u6MLtUF7U

**Comment by Matze997** [comment]
Return true and run the parent not in the return statement.
Its intentional to prevent too much entity updates on every tick

**Comment by kenzeve** [comment]
> Return true and run the parent not in the return statement. Its intentional to prevent too much entity updates on every tick

Well, your solution does fix my particular situation (but then it will tick non-stop even if there is no need), but as I mentioned this code works fine on 4.18.x, so definitely there's a behavioral change between 4.18 and 4.19

**Comment by dktapps** [comment]
I don't understand the issue. Are you saying it doesn't start ticking again when you return to the location?

**Comment by dktapps** [comment]
Technical detail: Simulation distance is usually smaller than render distance.

What happened here: The chunk containing the villager left your simulation distance and stopped being ticked (all fine so far).

However, when returning to the area, the chunk is _not_ re-registered as a ticking chunk, since it never left your render distance (i.e. [this code](https://github.com/pmmp/PocketMine-MP/blob/946c2fbacc1686e2c8a46e55e5300f8b02c80adb/src/player/Player.php#L810) is never executed).

The entity ticks when you're very close to it because [this code](https://github.com/pmmp/PocketMine-MP/blob/946c2fbacc1686e2c8a46e55e5300f8b02c80adb/src/player/Player.php#L1238) causes it to be scheduled for an update.
