### ISSUE TITLE
Turtle Shell Bug

### ISSUE THREAD

**Issue by gamegam** [pmmp/PocketMine-MP#5786]
### Issue description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### Steps to reproduce the issue
Turtle shells will not come off when equipped.

### OS and versions

* PocketMine-MP: 5.0.0
* PHP: 8.2
* Using JIT: yes/no (delete as appropriate) 
* Server OS: win10
* Game version: Android/iOS/Win10/Xbox/PS4/Switch (delete as appropriate)

### Plugins

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by dktapps** [comment]
Similar issues also affect 4.21.1.

This happens because the helmet re-sets itself into the inventory on every tick, causing a new itemstackID to be assigned each time this happens. This is problematic because it means that the client can't keep up with the itemstackID rotation, making it unable to remove the helmet.
