### ISSUE TITLE
Adding Player Effects

### ISSUE THREAD

**Issue by Amzy7** [pmmp/PocketMine-MP#6002]
### Issue description

- Expected result: What were you expecting to happen?
I was expecting to have the effect with the given time and amplifier

- Actual result: What actually happened?
The effect is added but with a 1 second duration instead of the duration time given. Ive noticed that this happens with some Effects and not all. The effects that this happens with is: Haste and Blindness. (Havent tested all).

### Steps to reproduce the issue
1. Add the line:
$event->getPlayer()->getEffects()->add(new EffectInstance(VanillaEffects::BLINDNESS(), $time, $amplifier, false));

2. Then get on the server and complete the action in order to get that effect.

### OS and versions

* PocketMine-MP: 5.4.2
* PHP:  PHP 8.1 (I think)

### Plugins

- If you remove all plugins, does the issue still occur?
I made a separate plugin with just this and it still occurs.

- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
On discord, Yes.
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
 $event->getPlayer()->getEffects()->add(new EffectInstance(VanillaEffects::BLINDNESS(), $time, $amplifier, false));

**Comment by jasonw4331** [comment]
This occurrence is very event specific due to the way pocketmine handles pre and post event types. In some situations the player's effects may be cleared or resynchronized with the player immediately following the code being ran triggering this behavior.

It's recommended to run your operation in a task which will run at the end of the tick instead during the middle of the event to avoid the behavior you are seeing.

**Comment by dktapps** [comment]
This is not enough code to understand what the issue is.
