### ISSUE TITLE
Air items with a count greater than 0 are not treated as null items 

### ISSUE THREAD

**Issue by TheNewHEROBRINEX** [pmmp/PocketMine-MP#6016]
### Issue description
It's possible to create an air item with a count greater than 0 (even just by doing `VanillaBlocks::AIR()->asItem()`) which will exhibit some unexpected behaviour. Examples:
- It can be converted by `TypeConverter::coreItemStackToNet()` just fine but can't be converted back by `TypeConverter::netItemStackToCore()` resulting in
  `pocketmine\network\mcpe\convert\TypeConversionException: "Item minecraft:air is not a blockitem, but runtime ID 11064 was provided"`.
- If set into a slot of the player inventory, no item can be moved into that slot anymore because of
 `pocketmine\network\mcpe\handler\ItemStackRequestProcessException: "Error processing action 0 (PlaceStackRequestAction): PlayerInventory#162909, slot: 2: Can only add items to an empty slot, or a slot containing the same item"`

### Steps to reproduce the issue
1. Have a plugin set an air item with a count greater than 0 inside your inventory
2. Notice you can't move items in that slot anymore.

### OS and versions

* PocketMine-MP: 5.5.0-BETA1
* PHP: 8.2.8
* Using JIT: no 
* Server OS: Ubuntu 22.04.3 LTS
* Game version: Linux (Android)

**Comment by dktapps** [comment]
For posterity:

- I think empty itemstacks ought to be represented by `null` in a future major version. However, this involves significant BC breaks.
- Air item and air block aren't actually required to be related at all. An air item cannot place an air block, so there's no obvious reason for them to be linked. However, again, this can't be changed without BC breaks.
- `Block->asItem()` probably ought to be able to return `NULL` even if we didn't use `null` for air items, as stuff like portal blocks aren't supposed to be obtainable as items anyway.

There's a couple of options for short term fixes to this:
- `Item->isNull()` to return `true` if the `id` is `ItemTypeIds::fromBlockTypeId(BlockTypeIds::AIR)` (perhaps an item-specific type ID is called for?)
- `Air->asItem()` to return a stack with count `0` - however, the same issue could still occur if using `setCount()` to any other value

**Comment by dktapps** [comment]
Possible next steps:
- A special item type (or null) for empty itemstacks, independent from the air block
- Make air blocks have a non-special-behaviour blockitem equivalent. This would permit stacking air (which is currently possible in Bedrock, as a blockitem does in fact exist for this, as seen here: https://github.com/pmmp/BedrockData/blob/master/required_item_list.json#L66-L69)

Changing `Block->asItem()` might be problematic due to the many places it's currently used, which would all start to become aware of blocks that might have no item (but really they do).
