### ISSUE TITLE
Server crash when you throw a Enderpearl

### ISSUE THREAD

**Issue by r3pt1s** [pmmp/PocketMine-MP#6490]
Link to crashdump: https://pastebin.com/zNJbuvST

### Additional comments (optional)
The server is crashing when you throw a Enderpearl while you just have that one Enderpearl
If you have 2 of them in your inventory, the first one will not crash but the second one will crash the server.
The server I tested this on was just a standalone PocketMine server with zero plugins.

Showcase: https://youtu.be/LsyKl0JUtlM
![Bild_2024-11-10_114746517](https://github.com/user-attachments/assets/d36c3bea-5a6f-41dd-b020-ee627f2993b6)

**Comment by dktapps** [comment]
@ipad54 can you look into this please, looks like it's cooldown related

Related to #6488

**Comment by ipad54** [comment]
This issue is caused because `ItemSerializer` can not serialize an item with 0 count in `onItemCooldownChanged()`. This can happen when you have 1 ender pearl since `resetItemCooldown()` is called only after a successful item usage, so ender pearl count is already decreased at this stage.

I’ll make a fix PR in about 2 hours (when I back home).
