### ISSUE TITLE
Could not connect: Outdated server!

### ISSUE THREAD

**Issue by PureCreation663** [pmmp/PocketMine-MP#820]
### Issue description

Connect to server from seemingly endlessly updated droid PE 

### Steps to reproduce the issue

1. ...Log into Server from MCPE v1.0.6

2. ...Green light Status but ... "Could not connect: Outdated server!"

### OS and versions

* PocketMine-v1.6.2dev.
* PHP:7?
* Server OS: Win10
* Game version: PE

### Crashdump, backtrace or other files

* ...

**Comment by Misteboss** [comment]
What branch are you using ? master or api3\network?

**Comment by PureCreation663** [comment]
I guess the API3...

<<This server is running PocketMine-MP version 1.6.2dev "Unleashed" (API
3.0.0-ALPHA4)>>

Thanks for the help and you all are the best!

**Comment by XDqrkneZ** [comment]
they haven't updated to 1.0.6 ;(

**Comment by AppleDevelops** [comment]
This will be closed, as it is considered spam.

**Comment by corytortoise** [comment]
You can use the api3/network branch for a version that supports mcpe 1.0.6. It isn't finished, and will continue to be changed, and it may have an effect on any plugins that use a lot of Item or NBT functions, but you can find a phar [here](https://poggit.pmmp.io/ci/pmmp/PocketMine-MP/~?branch=api3/network). In the future, you should really look on the forums, because this issue/question has been asked and answered there already.
