### ISSUE TITLE
freeze on command

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [pmmp/PocketMine-MP#84]
https://timings.aikar.co/?url=23424624

Someone freezed my server using command packet!
I had timings runing, and did /timings paste right after server went back to normal!

Do you know what it is? Or if pmmp is vulnerable at this kind of attack?

If u close the issue and ban me, at least give me a hint XD !

**Comment by TDMidkwhatisxd** [comment]
I searched on timings , many many times! It seems that spammimg commands = high loads! 
I will test tomorow! I will flood server with random commands, and then check the results!

**Comment by SOF3** [comment]
Please provide **clear** full steps to reproduce the issue, as well as the versions you are using. In simple words, please try to provide all information required in the issue template.

![.github/ISSUE_TEMPLATE.md](https://cloud.githubusercontent.com/assets/19623715/20035074/9e06ed12-a410-11e6-9d26-67749c42e78d.png)

By "clear", I mean that I don't want any subjective comments, but only simple steps to reproduce the issue. For description and other comments, please separate them.

This issue can be reopened if this issue is valid again after you have edited it properly.

**Comment by SOF3** [comment]
Some extra information I see from your timings report:

![Paste from **Elywing** at Fri, 4 Nov 2016 08:28:24 +0000](https://cloud.githubusercontent.com/assets/19623715/20035090/32cb1a5e-a411-11e6-971b-b7b0f1824a7d.png)

Interesting. I thought this is pmmp? And I thought Elywing was stable and totally no bugs?

![image](https://cloud.githubusercontent.com/assets/19623715/20035096/77e413e8-a411-11e6-8927-fa0c5afadb2b.png)

The /register command takes 5.44 seconds to execute every time. Hmm.. I don't think pmmp provides a command called /register by default...

**Please read the [contribution guidelines for creating an issue](../blob/master/CONTRIBUTING.md#creating-an-issue) before creating an issue!

From the above there is more than sufficient reason to declare this issue invalid.
