### ISSUE TITLE
PocketMine 1.6 has serious performance issues

### ISSUE THREAD

**Issue by mcpe4ever** [pmmp/PocketMine-MP#954]
### Issue description
PocketMine has serious performance issues.

With 80 players, pmmp can't keep up with 20TPS. Instead, I get 15TPS and a 128% server load according to timings. (This is without plugins)

Some of the biggest issues are:
```
receivePacket - ResourcePackClientResponsePacket [0x9] - taking 22ms
world - entityTick - taking 28ms with 80 players
```
Yes chunks take awhile too, but that is mostly out of our control (although strangely steadfast uses the old methods, and hacks it to work on new MCPE versions without subchunks...). However chunk utils by dktapps got chunk loading down to the same speed as steadfast, making this not a concern for me.

Network send & receive also do take a lot, but I believe that is out of our control.

Before dktapps fixed the Aysnc memory leak memory manager would constantly waste time doing GC (I was non the wiser with Aysnc-chunk-request turned on), but it seems like that is fixed now and memory manager never takes time on my timings. Now steadfast and pmmp have virtually the same memory usage which is great.

Something really seems wrong with entity ticking. Steadfast only takes 10-12ms to tick anywhere between 80-130 players. PMMP seems to be doing this twice as slow. I am not sure why, but something is taking a lot of time when ticking entities on PMMP.

This is going to be hard to reproduce to anyone without 80-130 players, so let me know if you want me to test something.

The slow ticking + terrible player join time combined is making PMMP run very slow. (When a player joins server file io is blocking the main thread for 1-2 seconds, though I think this is a known issue) 

### Steps to reproduce the issue
1. Start timings
2. Run for awhile.
3. Paste shocking results with resource packs & entity ticking.

### OS and versions

* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/645d744e057b26596c9553289e1f75e67a728ee0
* PHP: 7
* OS: Linux

**Comment by dktapps** [comment]
Steadfast vs PocketMine is not a valid comparison. Steadfast have stripped out 99% of everything that makes for a usable server for performance and their own uses.

**Comment by thebigsmileXD** [comment]
Indeed. Steadfast was a remove-any-feature version initially created for lifeboat. 
> Paste shocking results with resource packs & entity ticking.

resource packs are sendt once on join, maybe increase join settings in the yml (spawnhold etc, less network compression)
entity ticking can't be really critical, because only falling blocks, items and players really move.

**Comment by dktapps** [comment]
There are no performance issues with the average server not using resource packs. The spike for ResourcePackClientResponsePacket is due to the expensive part of the login sequence (I/O and NBT read) being executed after the resource packs sequence on login is completed, nothing to do with resource packs themselves.

**Comment by dktapps** [comment]
also, if you have 1-2 _seconds_ I/O time on join, you'd better get a new computer... even on my old machine it was 1-2 _milliseconds_. The bulk of the on-join load is due to NBT deserialization, which is extremely slow (see #466).

**Comment by dktapps** [comment]
Also:
> (although strangely steadfast uses the old methods, and hacks it to work on new MCPE versions without subchunks...). However chunk utils by dktapps got chunk loading down to the same speed as steadfast, making this not a concern for me.

- Steadfast doesn't support Anvil, and it's Anvil that my extension provides the performance improvement of. This statement makes no sense.
- Anvil and McRegion chunk conversion for the MCPE format is done in PocketMine on chunk load, whereas in Steadfast it is done on chunk send, and they do chunk network serialization on a different thread, which is why you don't see that issue on Steadfast. However, converting on send is less efficient than on load, especially if you have lots of players.
- PocketMine currently does disk I/O and chunk conversion to MCPE format on the main thread. This is a known major performance problem and work is underway to resolve this issue already.

**Comment by mcpe4ever** [comment]
@thebigsmileXD Not originally, before there new dev team took over steadfast was used just to add current pmmp features and while retaining 1.4 methods.

When MCPE 0.11 came out, lbsg had a major issue with lag because PocketMine 1.5 was very slow. They took a old pocketmine-soft build and backported it to support 0.11. The result: It was just as fast as the 0.10.5 Pocketmine builds, while having all the features of PocketMine 1.5.

All the original commits seen here never intended to strip features (they even wanted to maintain API compatibility with PocketMine, it was never supposed to be a "LBSG server software only" project):
https://github.com/Hydreon/Steadfast2/commits/master/src/pocketmine/Player.php?author=williamtdr

It is only recently the new LBSG team has started to strip things out and add crap like pets into the core.  The performance issues with 1.5 have been here for years.

These are some interesting issues:
https://github.com/PocketMine/PocketMine-MP/issues/3104
https://github.com/PocketMine/PocketMine-MP/issues/2567

**Comment by thebigsmileXD** [comment]
> also, if you have 1-2 seconds I/O time on join, you'd better get a new computer... even on my old machine it was 1-2 milliseconds. The bulk of the on-join load is due to NBT deserialization, which is extremely slow (see #466).

Sadly it takes about 5 seconds on my server, but as mentioned before, i had to play with the spawnhold settings to not lag out everyone when 2 players join at the same time.

If https://github.com/PocketMine/PocketMine-MP/issues/2567 is applying to you, i'd check the memory and caching settings.
